<?php

namespace Database\Seeders;

use App\Models\Achievement;
use Illuminate\Database\Seeder;

class AchievementSeeder extends Seeder
{
    public function run(): void
    {
        $achievements = [
            // === wins tier_group ===
            [
                'key' => 'first_victory',
                'name' => 'First Victory',
                'description' => 'Win your first game.',
                'icon' => 'trophy',
                'category' => 'milestone',
                'criteria' => ['type' => 'total_wins', 'count' => 1],
                'tier' => 1,
                'tier_group' => 'wins',
                'reward_xp' => 25,
            ],
            [
                'key' => 'warrior',
                'name' => 'Warrior',
                'description' => 'Win 5 games.',
                'icon' => 'shield',
                'category' => 'milestone',
                'criteria' => ['type' => 'total_wins', 'count' => 5],
                'tier' => 2,
                'tier_group' => 'wins',
                'reward_xp' => 50,
            ],
            [
                'key' => 'veteran',
                'name' => 'Veteran',
                'description' => 'Win 10 games.',
                'icon' => 'shield',
                'category' => 'milestone',
                'criteria' => ['type' => 'total_wins', 'count' => 10],
                'tier' => 3,
                'tier_group' => 'wins',
                'reward_xp' => 75,
            ],
            [
                'key' => 'champion',
                'name' => 'Champion',
                'description' => 'Win 50 games.',
                'icon' => 'crown',
                'category' => 'milestone',
                'criteria' => ['type' => 'total_wins', 'count' => 50],
                'tier' => 4,
                'tier_group' => 'wins',
                'reward_xp' => 200,
            ],

            // === streak tier_group ===
            [
                'key' => 'hot_streak_3',
                'name' => 'Hot Streak',
                'description' => 'Win 3 games in a row.',
                'icon' => 'flame',
                'category' => 'streak',
                'criteria' => ['type' => 'win_streak', 'count' => 3],
                'tier' => 1,
                'tier_group' => 'streak',
                'reward_xp' => 50,
            ],
            [
                'key' => 'unstoppable_5',
                'name' => 'Unstoppable',
                'description' => 'Win 5 games in a row.',
                'icon' => 'lightning',
                'category' => 'streak',
                'criteria' => ['type' => 'win_streak', 'count' => 5],
                'tier' => 2,
                'tier_group' => 'streak',
                'reward_xp' => 100,
            ],
            [
                'key' => 'legendary_streak',
                'name' => 'Legendary',
                'description' => 'Win 10 games in a row.',
                'icon' => 'lightning',
                'category' => 'streak',
                'criteria' => ['type' => 'win_streak', 'count' => 10],
                'tier' => 3,
                'tier_group' => 'streak',
                'reward_xp' => 250,
            ],

            // === duel tier_group ===
            [
                'key' => 'duelist',
                'name' => 'Duelist',
                'description' => 'Win 5 duel games.',
                'icon' => 'swords',
                'category' => 'duel',
                'criteria' => ['type' => 'duel_wins', 'count' => 5],
                'tier' => 1,
                'tier_group' => 'duel',
                'reward_xp' => 50,
            ],
            [
                'key' => 'duel_master',
                'name' => 'Duel Master',
                'description' => 'Win 25 duel games.',
                'icon' => 'crossed_swords',
                'category' => 'duel',
                'criteria' => ['type' => 'duel_wins', 'count' => 25],
                'tier' => 2,
                'tier_group' => 'duel',
                'reward_xp' => 150,
            ],

            // === level tier_group ===
            [
                'key' => 'level_5',
                'name' => 'Apprentice',
                'description' => 'Reach level 5.',
                'icon' => 'book',
                'category' => 'progression',
                'criteria' => ['type' => 'level_reached', 'value' => 5],
                'tier' => 1,
                'tier_group' => 'level',
                'reward_xp' => 25,
            ],
            [
                'key' => 'level_10',
                'name' => 'Adept',
                'description' => 'Reach level 10.',
                'icon' => 'wizard',
                'category' => 'progression',
                'criteria' => ['type' => 'level_reached', 'value' => 10],
                'tier' => 2,
                'tier_group' => 'level',
                'reward_xp' => 50,
            ],
            [
                'key' => 'level_20',
                'name' => 'Master Advisor',
                'description' => 'Reach level 20.',
                'icon' => 'castle',
                'category' => 'progression',
                'criteria' => ['type' => 'level_reached', 'value' => 20],
                'tier' => 3,
                'tier_group' => 'level',
                'reward_xp' => 150,
            ],

            // === elo tier_group ===
            [
                'key' => 'elo_1200',
                'name' => 'Rising Star',
                'description' => 'Reach an ELO rating of 1200.',
                'icon' => 'arrow_up',
                'category' => 'elo',
                'criteria' => ['type' => 'elo_reached', 'value' => 1200],
                'tier' => 1,
                'tier_group' => 'elo',
                'reward_xp' => 50,
            ],
            [
                'key' => 'elo_1500',
                'name' => 'Grand Master',
                'description' => 'Reach an ELO rating of 1500.',
                'icon' => 'diamond',
                'category' => 'elo',
                'criteria' => ['type' => 'elo_reached', 'value' => 1500],
                'tier' => 2,
                'tier_group' => 'elo',
                'reward_xp' => 150,
            ],

            // === login_streak tier_group ===
            [
                'key' => 'loyal_advisor',
                'name' => 'Loyal Advisor',
                'description' => 'Maintain a 3-day login streak.',
                'icon' => 'calendar',
                'category' => 'dedication',
                'criteria' => ['type' => 'login_streak', 'count' => 3],
                'tier' => 1,
                'tier_group' => 'login_streak',
                'reward_xp' => 25,
            ],
            [
                'key' => 'dedicated_advisor',
                'name' => 'Dedicated',
                'description' => 'Maintain a 7-day login streak.',
                'icon' => 'calendar',
                'category' => 'dedication',
                'criteria' => ['type' => 'login_streak', 'count' => 7],
                'tier' => 2,
                'tier_group' => 'login_streak',
                'reward_xp' => 50,
            ],
            [
                'key' => 'devoted_advisor',
                'name' => 'Devoted',
                'description' => 'Maintain a 14-day login streak.',
                'icon' => 'calendar',
                'category' => 'dedication',
                'criteria' => ['type' => 'login_streak', 'count' => 14],
                'tier' => 3,
                'tier_group' => 'login_streak',
                'reward_xp' => 100,
            ],

            // === social tier_group ===
            [
                'key' => 'ally_found',
                'name' => 'Ally Found',
                'description' => 'Make your first friend.',
                'icon' => 'handshake',
                'category' => 'social',
                'criteria' => ['type' => 'total_friends', 'count' => 1],
                'tier' => 1,
                'tier_group' => 'social',
                'reward_xp' => 25,
            ],
            [
                'key' => 'popular',
                'name' => 'Popular',
                'description' => 'Have 10 friends.',
                'icon' => 'handshake',
                'category' => 'social',
                'criteria' => ['type' => 'total_friends', 'count' => 10],
                'tier' => 2,
                'tier_group' => 'social',
                'reward_xp' => 75,
            ],

            // === online tier_group ===
            [
                'key' => 'networked',
                'name' => 'Networked',
                'description' => 'Complete 5 online games.',
                'icon' => 'globe',
                'category' => 'online',
                'criteria' => ['type' => 'online_plays', 'count' => 5],
                'tier' => 1,
                'tier_group' => 'online',
                'reward_xp' => 50,
            ],
            [
                'key' => 'arena_veteran',
                'name' => 'Arena Veteran',
                'description' => 'Complete 25 online games.',
                'icon' => 'globe',
                'category' => 'online',
                'criteria' => ['type' => 'online_plays', 'count' => 25],
                'tier' => 2,
                'tier_group' => 'online',
                'reward_xp' => 150,
            ],

            // === duel_plays tier_group ===
            [
                'key' => 'arena_regular',
                'name' => 'Arena Regular',
                'description' => 'Complete 10 duel games.',
                'icon' => 'swords',
                'category' => 'duel',
                'criteria' => ['type' => 'duel_plays', 'count' => 10],
                'tier' => 1,
                'tier_group' => 'duel_plays',
                'reward_xp' => 50,
            ],
            [
                'key' => 'arena_champion',
                'name' => 'Arena Champion',
                'description' => 'Complete 50 duel games.',
                'icon' => 'crossed_swords',
                'category' => 'duel',
                'criteria' => ['type' => 'duel_plays', 'count' => 50],
                'tier' => 2,
                'tier_group' => 'duel_plays',
                'reward_xp' => 200,
            ],

            // === solo tier_group ===
            [
                'key' => 'lone_advisor',
                'name' => 'Lone Advisor',
                'description' => 'Complete 5 solo games.',
                'icon' => 'person',
                'category' => 'milestone',
                'criteria' => ['type' => 'solo_plays', 'count' => 5],
                'tier' => 1,
                'tier_group' => 'solo',
                'reward_xp' => 25,
            ],
            [
                'key' => 'solo_master',
                'name' => 'Solo Master',
                'description' => 'Win 10 solo games.',
                'icon' => 'person',
                'category' => 'milestone',
                'criteria' => ['type' => 'solo_wins', 'count' => 10],
                'tier' => 2,
                'tier_group' => 'solo',
                'reward_xp' => 75,
            ],

            // === local (pass & play) tier_group ===
            [
                'key' => 'game_night',
                'name' => 'Game Night',
                'description' => 'Complete 5 local pass-and-play games.',
                'icon' => 'people',
                'category' => 'social',
                'criteria' => ['type' => 'local_plays', 'count' => 5],
                'tier' => 1,
                'tier_group' => 'local',
                'reward_xp' => 25,
            ],
            [
                'key' => 'tabletop_regular',
                'name' => 'Tabletop Regular',
                'description' => 'Complete 25 local pass-and-play games.',
                'icon' => 'people',
                'category' => 'social',
                'criteria' => ['type' => 'local_plays', 'count' => 25],
                'tier' => 2,
                'tier_group' => 'local',
                'reward_xp' => 100,
            ],

            // === coop tier_group ===
            [
                'key' => 'team_player',
                'name' => 'Team Player',
                'description' => 'Complete 10 cooperative games.',
                'icon' => 'handshake',
                'category' => 'milestone',
                'criteria' => ['type' => 'coop_plays', 'count' => 10],
                'tier' => 1,
                'tier_group' => 'coop',
                'reward_xp' => 25,
            ],
            [
                'key' => 'united_front',
                'name' => 'United Front',
                'description' => 'Win 10 cooperative games.',
                'icon' => 'handshake',
                'category' => 'milestone',
                'criteria' => ['type' => 'coop_wins', 'count' => 10],
                'tier' => 2,
                'tier_group' => 'coop',
                'reward_xp' => 75,
            ],

            // === online_wins tier_group ===
            [
                'key' => 'online_victor',
                'name' => 'Online Victor',
                'description' => 'Win 5 online games.',
                'icon' => 'globe',
                'category' => 'online',
                'criteria' => ['type' => 'online_wins', 'count' => 5],
                'tier' => 1,
                'tier_group' => 'online_wins',
                'reward_xp' => 50,
            ],
            [
                'key' => 'online_champion',
                'name' => 'Online Champion',
                'description' => 'Win 25 online games.',
                'icon' => 'globe',
                'category' => 'online',
                'criteria' => ['type' => 'online_wins', 'count' => 25],
                'tier' => 2,
                'tier_group' => 'online_wins',
                'reward_xp' => 200,
            ],

            // === single_classic tier_group ===
            [
                'key' => 'solo_classic_regular',
                'name' => 'Solo Adventurer',
                'description' => 'Complete 5 solo classic games.',
                'icon' => 'person',
                'category' => 'milestone',
                'criteria' => ['type' => 'single_classic_plays', 'count' => 5],
                'tier' => 1,
                'tier_group' => 'single_classic',
                'reward_xp' => 25,
            ],
            [
                'key' => 'solo_classic_victor',
                'name' => 'Solo Classic Victor',
                'description' => 'Win 10 solo classic games.',
                'icon' => 'person',
                'category' => 'milestone',
                'criteria' => ['type' => 'single_classic_wins', 'count' => 10],
                'tier' => 2,
                'tier_group' => 'single_classic',
                'reward_xp' => 75,
            ],

            // === single_duel tier_group ===
            [
                'key' => 'solo_duelist',
                'name' => 'Solo Duelist',
                'description' => 'Complete 5 solo duel games.',
                'icon' => 'swords',
                'category' => 'duel',
                'criteria' => ['type' => 'single_duel_plays', 'count' => 5],
                'tier' => 1,
                'tier_group' => 'single_duel',
                'reward_xp' => 25,
            ],
            [
                'key' => 'solo_duel_victor',
                'name' => 'Bot Slayer',
                'description' => 'Win 10 solo duel games.',
                'icon' => 'swords',
                'category' => 'duel',
                'criteria' => ['type' => 'single_duel_wins', 'count' => 10],
                'tier' => 2,
                'tier_group' => 'single_duel',
                'reward_xp' => 75,
            ],

            // === local_classic tier_group ===
            [
                'key' => 'local_classic_regular',
                'name' => 'Couch Co-op',
                'description' => 'Complete 5 local classic games.',
                'icon' => 'people',
                'category' => 'social',
                'criteria' => ['type' => 'local_classic_plays', 'count' => 5],
                'tier' => 1,
                'tier_group' => 'local_classic',
                'reward_xp' => 25,
            ],
            [
                'key' => 'local_classic_victor',
                'name' => 'Local Legend',
                'description' => 'Win 10 local classic games.',
                'icon' => 'people',
                'category' => 'social',
                'criteria' => ['type' => 'local_classic_wins', 'count' => 10],
                'tier' => 2,
                'tier_group' => 'local_classic',
                'reward_xp' => 75,
            ],

            // === local_duel tier_group ===
            [
                'key' => 'local_duel_regular',
                'name' => 'Friendly Rivals',
                'description' => 'Complete 5 local duel games.',
                'icon' => 'swords',
                'category' => 'social',
                'criteria' => ['type' => 'local_duel_plays', 'count' => 5],
                'tier' => 1,
                'tier_group' => 'local_duel',
                'reward_xp' => 25,
            ],
            [
                'key' => 'local_duel_victor',
                'name' => 'Couch Champion',
                'description' => 'Win 10 local duel games.',
                'icon' => 'swords',
                'category' => 'social',
                'criteria' => ['type' => 'local_duel_wins', 'count' => 10],
                'tier' => 2,
                'tier_group' => 'local_duel',
                'reward_xp' => 75,
            ],

            // === online_classic tier_group ===
            [
                'key' => 'online_classic_regular',
                'name' => 'Online Cooperator',
                'description' => 'Complete 5 online classic games.',
                'icon' => 'globe',
                'category' => 'online',
                'criteria' => ['type' => 'online_classic_plays', 'count' => 5],
                'tier' => 1,
                'tier_group' => 'online_classic',
                'reward_xp' => 50,
            ],
            [
                'key' => 'online_classic_victor',
                'name' => 'Online Classic Champion',
                'description' => 'Win 10 online classic games.',
                'icon' => 'globe',
                'category' => 'online',
                'criteria' => ['type' => 'online_classic_wins', 'count' => 10],
                'tier' => 2,
                'tier_group' => 'online_classic',
                'reward_xp' => 100,
            ],

            // === online_duel tier_group ===
            [
                'key' => 'online_duel_regular',
                'name' => 'Online Challenger',
                'description' => 'Complete 5 online duel games.',
                'icon' => 'crossed_swords',
                'category' => 'online',
                'criteria' => ['type' => 'online_duel_plays', 'count' => 5],
                'tier' => 1,
                'tier_group' => 'online_duel',
                'reward_xp' => 50,
            ],
            [
                'key' => 'online_duel_victor',
                'name' => 'Online Duel Champion',
                'description' => 'Win 10 online duel games.',
                'icon' => 'crossed_swords',
                'category' => 'online',
                'criteria' => ['type' => 'online_duel_wins', 'count' => 10],
                'tier' => 2,
                'tier_group' => 'online_duel',
                'reward_xp' => 100,
            ],

            // === Standalone (no tier_group) ===
            [
                'key' => 'seasoned_player',
                'name' => 'Seasoned Player',
                'description' => 'Play 50 games.',
                'icon' => 'scroll',
                'category' => 'milestone',
                'criteria' => ['type' => 'games_played', 'count' => 50],
                'tier' => 1,
                'tier_group' => null,
                'reward_xp' => 75,
            ],
            [
                'key' => 'perfect_kingdom',
                'name' => 'Perfect Kingdom',
                'description' => 'Finish a game with 3 stats at maximum.',
                'icon' => 'star',
                'category' => 'excellence',
                'criteria' => ['type' => 'perfect_stats', 'count' => 3],
                'tier' => 1,
                'tier_group' => null,
                'reward_xp' => 100,
            ],
            [
                'key' => 'diverse_counsel',
                'name' => 'Diverse Counsel',
                'description' => 'Play with 5 different characters.',
                'icon' => 'people',
                'category' => 'exploration',
                'criteria' => ['type' => 'unique_characters', 'count' => 5],
                'tier' => 1,
                'tier_group' => null,
                'reward_xp' => 50,
            ],
            [
                'key' => 'underdog_victory',
                'name' => 'Underdog Victory',
                'description' => 'Win a game with all stats below 5.',
                'icon' => 'muscle',
                'category' => 'challenge',
                'criteria' => ['type' => 'all_stats_below', 'value' => 5],
                'tier' => 1,
                'tier_group' => null,
                'reward_xp' => 200,
            ],
            [
                'key' => 'golden_age',
                'name' => 'Golden Age',
                'description' => 'Win a game with all stats above 18.',
                'icon' => 'sparkles',
                'category' => 'excellence',
                'criteria' => ['type' => 'all_stats_above', 'value' => 18],
                'tier' => 1,
                'tier_group' => null,
                'reward_xp' => 200,
            ],
            [
                'key' => 'versatile_victor',
                'name' => 'Versatile Victor',
                'description' => 'Win games with 5 different characters.',
                'icon' => 'people',
                'category' => 'exploration',
                'criteria' => ['type' => 'wins_with_characters', 'count' => 5],
                'tier' => 1,
                'tier_group' => null,
                'reward_xp' => 100,
            ],
        ];

        foreach ($achievements as $data) {
            Achievement::updateOrCreate(
                ['key' => $data['key']],
                $data
            );
        }
    }
}
