<?php

namespace Database\Seeders;

use App\Models\Character;
use App\Models\CharacterLevelOption;
use Illuminate\Database\Seeder;

class CharacterLevelOptionSeeder extends Seeder
{
    public function run(): void
    {
        // Remove old generic (non-character-specific) options
        CharacterLevelOption::whereNull('character_id')->delete();

        // Use character IDs by position — update names here if characters change
        $characters = Character::orderBy('id')->limit(6)->pluck('id');
        $william = $characters[0] ?? null;   // Lord Reginald (Diplomat)
        $aurelia = $characters[1] ?? null;   // Dame Ironside (Knight)
        $aldric = $characters[2] ?? null;    // Brother Ambrose (Holy Man)
        $oswald = $characters[3] ?? null;    // Margery the Coinbiter (Merchant)
        $meredith = $characters[4] ?? null;  // Whisper (Spy)
        $godwin = $characters[5] ?? null;    // Old Godwin (Scholar)

        $options = [
            // =============================================
            // LORD WILLIAM — The Diplomat
            // =============================================
            [
                'name' => 'Diplomatic Training',
                'type' => 'bump_dice_face',
                'config' => null,
                'available_at_level' => 1,
                'character_id' => $william,
                'max_selections' => 0,
                'sort_order' => 10,
                'description' => 'Years in court have sharpened your edge. +1 to a die face.',
                'icon' => 'dice',
            ],
            [
                'name' => 'Silver Tongue',
                'type' => 'bump_dice_face',
                'config' => null,
                'available_at_level' => 2,
                'character_id' => $william,
                'max_selections' => 0,
                'sort_order' => 11,
                'description' => 'Your words carry more weight than swords. +1 to a die face.',
                'icon' => 'dice',
            ],
            [
                'name' => 'Political Mastery',
                'type' => 'bump_two_dice_faces',
                'config' => null,
                'available_at_level' => 3,
                'character_id' => $william,
                'max_selections' => 2,
                'sort_order' => 20,
                'description' => 'Command both word and deed with equal skill. +1 to two die faces.',
                'icon' => 'dice-multiple',
            ],
            [
                'name' => 'Court Favour',
                'type' => 'passive_stat_bonus',
                'config' => ['stat' => 'influence', 'value' => 1],
                'available_at_level' => 1,
                'character_id' => $william,
                'max_selections' => 1,
                'sort_order' => 50,
                'description' => 'Your reputation precedes you. Start with +1 Influence.',
                'icon' => 'crown',
            ],
            [
                'name' => 'Treasury Connections',
                'type' => 'passive_stat_bonus',
                'config' => ['stat' => 'wealth', 'value' => 1],
                'available_at_level' => 2,
                'character_id' => $william,
                'max_selections' => 1,
                'sort_order' => 51,
                'description' => 'Friends in the exchequer open coffers. Start with +1 Wealth.',
                'icon' => 'coins',
            ],
            [
                'name' => 'Popular Support',
                'type' => 'passive_stat_bonus',
                'config' => ['stat' => 'happiness', 'value' => 1],
                'available_at_level' => 1,
                'character_id' => $william,
                'max_selections' => 1,
                'sort_order' => 52,
                'description' => 'The people adore a good speaker. Start with +1 Happiness.',
                'icon' => 'smile',
            ],
            [
                'name' => 'Royal Seal',
                'type' => 'start_with_item',
                'config' => ['random' => true],
                'available_at_level' => 2,
                'character_id' => $william,
                'max_selections' => 1,
                'sort_order' => 30,
                'description' => 'Your noble rank grants you resources. Start with a random item.',
                'icon' => 'backpack',
            ],
            [
                'name' => 'Diplomat\'s Pouch',
                'type' => 'extra_item_slot',
                'config' => null,
                'available_at_level' => 3,
                'character_id' => $william,
                'max_selections' => 2,
                'sort_order' => 40,
                'description' => 'Always carry letters and gifts of state. +1 item slot.',
                'icon' => 'bag',
            ],
            [
                'name' => 'Treaty of Alliance',
                'type' => 'bump_dice_face',
                'config' => null,
                'available_at_level' => 4,
                'character_id' => $william,
                'max_selections' => 0,
                'sort_order' => 12,
                'description' => 'Alliances forged in ink strengthen your hand. +1 to a die face.',
                'icon' => 'dice',
            ],
            [
                'name' => 'Eyes of the Court',
                'type' => 'card_redraw',
                'config' => null,
                'available_at_level' => 4,
                'character_id' => $william,
                'max_selections' => 1,
                'sort_order' => 70,
                'description' => 'Courtiers whisper the kingdom\'s secrets to you. Redraw a card once per game.',
                'icon' => 'eye',
            ],
            [
                'name' => 'Noble Sacrifice',
                'type' => 'start_with_curse',
                'config' => ['random' => true],
                'available_at_level' => 5,
                'character_id' => $william,
                'max_selections' => 1,
                'sort_order' => 80,
                'description' => 'Shoulder the kingdom\'s burdens willingly. Start each game with a random curse.',
                'icon' => 'skull',
            ],
            [
                'name' => 'Inner Circle',
                'type' => 'bump_two_dice_faces',
                'config' => null,
                'available_at_level' => 5,
                'character_id' => $william,
                'max_selections' => 2,
                'sort_order' => 21,
                'description' => 'Your closest allies amplify your every move. +1 to two die faces.',
                'icon' => 'dice-multiple',
            ],
            [
                'name' => 'Crown\'s Authority',
                'type' => 'add_wild',
                'config' => null,
                'available_at_level' => 6,
                'character_id' => $william,
                'max_selections' => 1,
                'sort_order' => 60,
                'description' => 'Speak with the voice of the crown itself. Replace a die face with WILD.',
                'icon' => 'star',
            ],
            [
                'name' => 'Feast of Lords',
                'type' => 'passive_stat_bonus',
                'config' => ['stat' => 'food', 'value' => 1],
                'available_at_level' => 3,
                'character_id' => $william,
                'max_selections' => 1,
                'sort_order' => 53,
                'description' => 'Your banquets forge bonds and fill bellies. Start with +1 Food.',
                'icon' => 'wheat',
            ],
            [
                'name' => 'Ambassador\'s Immunity',
                'type' => 'card_redraw',
                'config' => null,
                'available_at_level' => 5,
                'character_id' => $william,
                'max_selections' => 1,
                'sort_order' => 71,
                'description' => 'Diplomatic immunity lets you sidestep disaster. Redraw a card once per game.',
                'icon' => 'eye',
            ],
            [
                'name' => 'Grand Oration',
                'type' => 'bump_dice_face',
                'config' => null,
                'available_at_level' => 6,
                'character_id' => $william,
                'max_selections' => 0,
                'sort_order' => 13,
                'description' => 'Your speeches can move mountains. +1 to a die face.',
                'icon' => 'dice',
            ],

            // =============================================
            // DAME AURELIA — The Knight
            // =============================================
            [
                'name' => 'Combat Drills',
                'type' => 'bump_dice_face',
                'config' => null,
                'available_at_level' => 1,
                'character_id' => $aurelia,
                'max_selections' => 0,
                'sort_order' => 10,
                'description' => 'Daily training hones your martial skill. +1 to a die face.',
                'icon' => 'dice',
            ],
            [
                'name' => 'Shield Wall',
                'type' => 'passive_stat_bonus',
                'config' => ['stat' => 'security', 'value' => 1],
                'available_at_level' => 1,
                'character_id' => $aurelia,
                'max_selections' => 1,
                'sort_order' => 50,
                'description' => 'Your presence fortifies the realm\'s defences. Start with +1 Security.',
                'icon' => 'shield',
            ],
            [
                'name' => 'Battlefield Provisions',
                'type' => 'passive_stat_bonus',
                'config' => ['stat' => 'food', 'value' => 1],
                'available_at_level' => 2,
                'character_id' => $aurelia,
                'max_selections' => 1,
                'sort_order' => 51,
                'description' => 'A commander must keep troops fed. Start with +1 Food.',
                'icon' => 'wheat',
            ],
            [
                'name' => 'Weapon Master',
                'type' => 'bump_dice_face',
                'config' => null,
                'available_at_level' => 2,
                'character_id' => $aurelia,
                'max_selections' => 0,
                'sort_order' => 11,
                'description' => 'Master a new weapon form. +1 to a die face.',
                'icon' => 'dice',
            ],
            [
                'name' => 'Dual Wield',
                'type' => 'bump_two_dice_faces',
                'config' => null,
                'available_at_level' => 3,
                'character_id' => $aurelia,
                'max_selections' => 2,
                'sort_order' => 20,
                'description' => 'Strike with both blade and shield in tandem. +1 to two die faces.',
                'icon' => 'dice-multiple',
            ],
            [
                'name' => 'Squire\'s Kit',
                'type' => 'start_with_item',
                'config' => ['random' => true],
                'available_at_level' => 2,
                'character_id' => $aurelia,
                'max_selections' => 1,
                'sort_order' => 30,
                'description' => 'Your squire packs supplies for every campaign. Start with a random item.',
                'icon' => 'backpack',
            ],
            [
                'name' => 'War Chest',
                'type' => 'extra_item_slot',
                'config' => null,
                'available_at_level' => 3,
                'character_id' => $aurelia,
                'max_selections' => 2,
                'sort_order' => 40,
                'description' => 'A seasoned knight carries more than just a sword. +1 item slot.',
                'icon' => 'bag',
            ],
            [
                'name' => 'Tactical Retreat',
                'type' => 'card_redraw',
                'config' => null,
                'available_at_level' => 4,
                'character_id' => $aurelia,
                'max_selections' => 1,
                'sort_order' => 70,
                'description' => 'Know when to fall back and regroup. Redraw a card once per game.',
                'icon' => 'eye',
            ],
            [
                'name' => 'Vanguard Training',
                'type' => 'bump_dice_face',
                'config' => null,
                'available_at_level' => 4,
                'character_id' => $aurelia,
                'max_selections' => 0,
                'sort_order' => 12,
                'description' => 'Lead the charge with devastating force. +1 to a die face.',
                'icon' => 'dice',
            ],
            [
                'name' => 'Fortify Position',
                'type' => 'passive_stat_bonus',
                'config' => ['stat' => 'security', 'value' => 1],
                'available_at_level' => 3,
                'character_id' => $aurelia,
                'max_selections' => 1,
                'sort_order' => 52,
                'description' => 'Build stronger defences wherever you stand. Start with +1 Security.',
                'icon' => 'shield',
            ],
            [
                'name' => 'Blood Oath',
                'type' => 'start_with_curse',
                'config' => ['random' => true],
                'available_at_level' => 5,
                'character_id' => $aurelia,
                'max_selections' => 1,
                'sort_order' => 80,
                'description' => 'Swear a dangerous oath for battlefield glory. Start each game with a random curse.',
                'icon' => 'skull',
            ],
            [
                'name' => 'Knight Commander',
                'type' => 'bump_two_dice_faces',
                'config' => null,
                'available_at_level' => 5,
                'character_id' => $aurelia,
                'max_selections' => 2,
                'sort_order' => 21,
                'description' => 'Command your forces with devastating precision. +1 to two die faces.',
                'icon' => 'dice-multiple',
            ],
            [
                'name' => 'Champion\'s Resolve',
                'type' => 'add_wild',
                'config' => null,
                'available_at_level' => 6,
                'character_id' => $aurelia,
                'max_selections' => 1,
                'sort_order' => 60,
                'description' => 'Channel your warrior spirit into pure power. Replace a die face with WILD.',
                'icon' => 'star',
            ],
            [
                'name' => 'Inspiring Charge',
                'type' => 'passive_stat_bonus',
                'config' => ['stat' => 'influence', 'value' => 1],
                'available_at_level' => 4,
                'character_id' => $aurelia,
                'max_selections' => 1,
                'sort_order' => 53,
                'description' => 'Your bravery inspires the whole kingdom. Start with +1 Influence.',
                'icon' => 'crown',
            ],
            [
                'name' => 'Siege Breaker',
                'type' => 'bump_dice_face',
                'config' => null,
                'available_at_level' => 5,
                'character_id' => $aurelia,
                'max_selections' => 0,
                'sort_order' => 13,
                'description' => 'No wall can stand before your assault. +1 to a die face.',
                'icon' => 'dice',
            ],
            [
                'name' => 'Arms Cache',
                'type' => 'extra_item_slot',
                'config' => null,
                'available_at_level' => 6,
                'character_id' => $aurelia,
                'max_selections' => 2,
                'sort_order' => 41,
                'description' => 'Maintain a personal armoury for every occasion. +1 item slot.',
                'icon' => 'bag',
            ],

            // =============================================
            // BROTHER ALDRIC — The Holy Man
            // =============================================
            [
                'name' => 'Morning Prayers',
                'type' => 'bump_dice_face',
                'config' => null,
                'available_at_level' => 1,
                'character_id' => $aldric,
                'max_selections' => 0,
                'sort_order' => 10,
                'description' => 'Dawn devotions sharpen divine favour. +1 to a die face.',
                'icon' => 'dice',
            ],
            [
                'name' => 'Blessed Ground',
                'type' => 'passive_stat_bonus',
                'config' => ['stat' => 'religion', 'value' => 1],
                'available_at_level' => 1,
                'character_id' => $aldric,
                'max_selections' => 1,
                'sort_order' => 50,
                'description' => 'Sacred rites strengthen the realm\'s faith. Start with +1 Religion.',
                'icon' => 'church',
            ],
            [
                'name' => 'Alms for the Poor',
                'type' => 'passive_stat_bonus',
                'config' => ['stat' => 'happiness', 'value' => 1],
                'available_at_level' => 1,
                'character_id' => $aldric,
                'max_selections' => 1,
                'sort_order' => 51,
                'description' => 'Charity warms the hearts of the people. Start with +1 Happiness.',
                'icon' => 'smile',
            ],
            [
                'name' => 'Scripture Study',
                'type' => 'bump_dice_face',
                'config' => null,
                'available_at_level' => 2,
                'character_id' => $aldric,
                'max_selections' => 0,
                'sort_order' => 11,
                'description' => 'Ancient texts reveal hidden strengths. +1 to a die face.',
                'icon' => 'dice',
            ],
            [
                'name' => 'Sacred Relics',
                'type' => 'start_with_item',
                'config' => ['random' => true],
                'available_at_level' => 2,
                'character_id' => $aldric,
                'max_selections' => 1,
                'sort_order' => 30,
                'description' => 'Holy artefacts bless your endeavours. Start with a random item.',
                'icon' => 'backpack',
            ],
            [
                'name' => 'Pilgrim\'s Pack',
                'type' => 'extra_item_slot',
                'config' => null,
                'available_at_level' => 3,
                'character_id' => $aldric,
                'max_selections' => 2,
                'sort_order' => 40,
                'description' => 'Carry relics and remedies for every trial. +1 item slot.',
                'icon' => 'bag',
            ],
            [
                'name' => 'Divine Revelation',
                'type' => 'bump_two_dice_faces',
                'config' => null,
                'available_at_level' => 3,
                'character_id' => $aldric,
                'max_selections' => 2,
                'sort_order' => 20,
                'description' => 'God illuminates two paths at once. +1 to two die faces.',
                'icon' => 'dice-multiple',
            ],
            [
                'name' => 'Prophetic Vision',
                'type' => 'card_redraw',
                'config' => null,
                'available_at_level' => 4,
                'character_id' => $aldric,
                'max_selections' => 1,
                'sort_order' => 70,
                'description' => 'Foresee the trials that lie ahead. Redraw a card once per game.',
                'icon' => 'eye',
            ],
            [
                'name' => 'Monastic Discipline',
                'type' => 'bump_dice_face',
                'config' => null,
                'available_at_level' => 4,
                'character_id' => $aldric,
                'max_selections' => 0,
                'sort_order' => 12,
                'description' => 'Years of fasting forge an iron will. +1 to a die face.',
                'icon' => 'dice',
            ],
            [
                'name' => 'Harvest Blessing',
                'type' => 'passive_stat_bonus',
                'config' => ['stat' => 'food', 'value' => 1],
                'available_at_level' => 3,
                'character_id' => $aldric,
                'max_selections' => 1,
                'sort_order' => 52,
                'description' => 'Bless the fields and the harvest will follow. Start with +1 Food.',
                'icon' => 'wheat',
            ],
            [
                'name' => 'Martyr\'s Burden',
                'type' => 'start_with_curse',
                'config' => ['random' => true],
                'available_at_level' => 5,
                'character_id' => $aldric,
                'max_selections' => 1,
                'sort_order' => 80,
                'description' => 'Shoulder suffering willingly for divine favour. Start each game with a random curse.',
                'icon' => 'skull',
            ],
            [
                'name' => 'Consecrated Hands',
                'type' => 'bump_two_dice_faces',
                'config' => null,
                'available_at_level' => 5,
                'character_id' => $aldric,
                'max_selections' => 2,
                'sort_order' => 21,
                'description' => 'Every touch carries heaven\'s blessing. +1 to two die faces.',
                'icon' => 'dice-multiple',
            ],
            [
                'name' => 'Miracle Worker',
                'type' => 'add_wild',
                'config' => null,
                'available_at_level' => 6,
                'character_id' => $aldric,
                'max_selections' => 1,
                'sort_order' => 60,
                'description' => 'Channel the purest divine energy. Replace a die face with WILD.',
                'icon' => 'star',
            ],
            [
                'name' => 'Temple Treasury',
                'type' => 'passive_stat_bonus',
                'config' => ['stat' => 'wealth', 'value' => 1],
                'available_at_level' => 4,
                'character_id' => $aldric,
                'max_selections' => 1,
                'sort_order' => 53,
                'description' => 'The faithful tithe generously to your cause. Start with +1 Wealth.',
                'icon' => 'coins',
            ],
            [
                'name' => 'Absolution',
                'type' => 'card_redraw',
                'config' => null,
                'available_at_level' => 5,
                'character_id' => $aldric,
                'max_selections' => 1,
                'sort_order' => 71,
                'description' => 'Cleanse the sins that would doom the kingdom. Redraw a card once per game.',
                'icon' => 'eye',
            ],
            [
                'name' => 'Holy Vigil',
                'type' => 'bump_dice_face',
                'config' => null,
                'available_at_level' => 6,
                'character_id' => $aldric,
                'max_selections' => 0,
                'sort_order' => 13,
                'description' => 'Sleepless prayer grants supernatural focus. +1 to a die face.',
                'icon' => 'dice',
            ],

            // =============================================
            // OSWALD THE TRADER — The Merchant
            // =============================================
            [
                'name' => 'Market Savvy',
                'type' => 'bump_dice_face',
                'config' => null,
                'available_at_level' => 1,
                'character_id' => $oswald,
                'max_selections' => 0,
                'sort_order' => 10,
                'description' => 'A trader\'s instincts never fail. +1 to a die face.',
                'icon' => 'dice',
            ],
            [
                'name' => 'Trade Routes',
                'type' => 'passive_stat_bonus',
                'config' => ['stat' => 'wealth', 'value' => 1],
                'available_at_level' => 1,
                'character_id' => $oswald,
                'max_selections' => 1,
                'sort_order' => 50,
                'description' => 'Established trade lines fill your coffers. Start with +1 Wealth.',
                'icon' => 'coins',
            ],
            [
                'name' => 'Smuggler\'s Stash',
                'type' => 'start_with_item',
                'config' => ['random' => true],
                'available_at_level' => 1,
                'character_id' => $oswald,
                'max_selections' => 1,
                'sort_order' => 30,
                'description' => 'Always have something valuable tucked away. Start with a random item.',
                'icon' => 'backpack',
            ],
            [
                'name' => 'Haggling',
                'type' => 'bump_dice_face',
                'config' => null,
                'available_at_level' => 2,
                'character_id' => $oswald,
                'max_selections' => 0,
                'sort_order' => 11,
                'description' => 'Never accept the first offer. +1 to a die face.',
                'icon' => 'dice',
            ],
            [
                'name' => 'Merchant\'s Vault',
                'type' => 'extra_item_slot',
                'config' => null,
                'available_at_level' => 2,
                'character_id' => $oswald,
                'max_selections' => 2,
                'sort_order' => 40,
                'description' => 'A bigger vault means more opportunities. +1 item slot.',
                'icon' => 'bag',
            ],
            [
                'name' => 'Caravan Guard',
                'type' => 'passive_stat_bonus',
                'config' => ['stat' => 'security', 'value' => 1],
                'available_at_level' => 2,
                'character_id' => $oswald,
                'max_selections' => 1,
                'sort_order' => 51,
                'description' => 'Protect your investments with hired swords. Start with +1 Security.',
                'icon' => 'shield',
            ],
            [
                'name' => 'Double Down',
                'type' => 'bump_two_dice_faces',
                'config' => null,
                'available_at_level' => 3,
                'character_id' => $oswald,
                'max_selections' => 2,
                'sort_order' => 20,
                'description' => 'Bet big on two ventures at once. +1 to two die faces.',
                'icon' => 'dice-multiple',
            ],
            [
                'name' => 'Insider Trading',
                'type' => 'card_redraw',
                'config' => null,
                'available_at_level' => 4,
                'character_id' => $oswald,
                'max_selections' => 1,
                'sort_order' => 70,
                'description' => 'Know what\'s coming before everyone else. Redraw a card once per game.',
                'icon' => 'eye',
            ],
            [
                'name' => 'Luxury Imports',
                'type' => 'passive_stat_bonus',
                'config' => ['stat' => 'happiness', 'value' => 1],
                'available_at_level' => 3,
                'character_id' => $oswald,
                'max_selections' => 1,
                'sort_order' => 52,
                'description' => 'Exotic goods delight the populace. Start with +1 Happiness.',
                'icon' => 'smile',
            ],
            [
                'name' => 'Risky Investment',
                'type' => 'start_with_curse',
                'config' => ['random' => true],
                'available_at_level' => 4,
                'character_id' => $oswald,
                'max_selections' => 1,
                'sort_order' => 80,
                'description' => 'High risk, high reward — a trader\'s creed. Start each game with a random curse.',
                'icon' => 'skull',
            ],
            [
                'name' => 'Market Monopoly',
                'type' => 'bump_dice_face',
                'config' => null,
                'available_at_level' => 4,
                'character_id' => $oswald,
                'max_selections' => 0,
                'sort_order' => 12,
                'description' => 'Corner the market and reap the rewards. +1 to a die face.',
                'icon' => 'dice',
            ],
            [
                'name' => 'Trade Empire',
                'type' => 'bump_two_dice_faces',
                'config' => null,
                'available_at_level' => 5,
                'character_id' => $oswald,
                'max_selections' => 2,
                'sort_order' => 21,
                'description' => 'Your commercial empire spans the realm. +1 to two die faces.',
                'icon' => 'dice-multiple',
            ],
            [
                'name' => 'Golden Touch',
                'type' => 'add_wild',
                'config' => null,
                'available_at_level' => 6,
                'character_id' => $oswald,
                'max_selections' => 1,
                'sort_order' => 60,
                'description' => 'Everything you touch turns to gold. Replace a die face with WILD.',
                'icon' => 'star',
            ],
            [
                'name' => 'Feast Supplier',
                'type' => 'passive_stat_bonus',
                'config' => ['stat' => 'food', 'value' => 1],
                'available_at_level' => 3,
                'character_id' => $oswald,
                'max_selections' => 1,
                'sort_order' => 53,
                'description' => 'Your warehouses feed the kingdom in lean times. Start with +1 Food.',
                'icon' => 'wheat',
            ],
            [
                'name' => 'War Profiteer',
                'type' => 'bump_dice_face',
                'config' => null,
                'available_at_level' => 5,
                'character_id' => $oswald,
                'max_selections' => 0,
                'sort_order' => 13,
                'description' => 'Every conflict is a business opportunity. +1 to a die face.',
                'icon' => 'dice',
            ],
            [
                'name' => 'Second Warehouse',
                'type' => 'extra_item_slot',
                'config' => null,
                'available_at_level' => 5,
                'character_id' => $oswald,
                'max_selections' => 2,
                'sort_order' => 41,
                'description' => 'Expand your storage for more goods. +1 item slot.',
                'icon' => 'bag',
            ],

            // =============================================
            // MEREDITH THE SHADOW — The Spy
            // =============================================
            [
                'name' => 'Sleight of Hand',
                'type' => 'bump_dice_face',
                'config' => null,
                'available_at_level' => 1,
                'character_id' => $meredith,
                'max_selections' => 0,
                'sort_order' => 10,
                'description' => 'Quick fingers and quicker wits. +1 to a die face.',
                'icon' => 'dice',
            ],
            [
                'name' => 'Informant Network',
                'type' => 'passive_stat_bonus',
                'config' => ['stat' => 'influence', 'value' => 1],
                'available_at_level' => 1,
                'character_id' => $meredith,
                'max_selections' => 1,
                'sort_order' => 50,
                'description' => 'Whispered secrets buy power. Start with +1 Influence.',
                'icon' => 'crown',
            ],
            [
                'name' => 'Hidden Blade',
                'type' => 'passive_stat_bonus',
                'config' => ['stat' => 'security', 'value' => 1],
                'available_at_level' => 1,
                'character_id' => $meredith,
                'max_selections' => 1,
                'sort_order' => 51,
                'description' => 'Always carry protection unseen. Start with +1 Security.',
                'icon' => 'shield',
            ],
            [
                'name' => 'Lockpicking',
                'type' => 'bump_dice_face',
                'config' => null,
                'available_at_level' => 2,
                'character_id' => $meredith,
                'max_selections' => 0,
                'sort_order' => 11,
                'description' => 'No door stays closed for long. +1 to a die face.',
                'icon' => 'dice',
            ],
            [
                'name' => 'Spy\'s Satchel',
                'type' => 'start_with_item',
                'config' => ['random' => true],
                'available_at_level' => 2,
                'character_id' => $meredith,
                'max_selections' => 1,
                'sort_order' => 30,
                'description' => 'A bag of tricks for every occasion. Start with a random item.',
                'icon' => 'backpack',
            ],
            [
                'name' => 'Dead Drop',
                'type' => 'extra_item_slot',
                'config' => null,
                'available_at_level' => 3,
                'character_id' => $meredith,
                'max_selections' => 2,
                'sort_order' => 40,
                'description' => 'Stash equipment where others cannot find it. +1 item slot.',
                'icon' => 'bag',
            ],
            [
                'name' => 'Double Agent',
                'type' => 'bump_two_dice_faces',
                'config' => null,
                'available_at_level' => 3,
                'character_id' => $meredith,
                'max_selections' => 2,
                'sort_order' => 20,
                'description' => 'Play both sides to your advantage. +1 to two die faces.',
                'icon' => 'dice-multiple',
            ],
            [
                'name' => 'Coded Messages',
                'type' => 'card_redraw',
                'config' => null,
                'available_at_level' => 4,
                'character_id' => $meredith,
                'max_selections' => 1,
                'sort_order' => 70,
                'description' => 'Intercept intelligence before it reaches the enemy. Redraw a card once per game.',
                'icon' => 'eye',
            ],
            [
                'name' => 'Poison Craft',
                'type' => 'bump_dice_face',
                'config' => null,
                'available_at_level' => 4,
                'character_id' => $meredith,
                'max_selections' => 0,
                'sort_order' => 12,
                'description' => 'A subtle touch with deadly consequences. +1 to a die face.',
                'icon' => 'dice',
            ],
            [
                'name' => 'Shadow Pact',
                'type' => 'start_with_curse',
                'config' => ['random' => true],
                'available_at_level' => 5,
                'character_id' => $meredith,
                'max_selections' => 1,
                'sort_order' => 80,
                'description' => 'Dark deals bring dark power. Start each game with a random curse.',
                'icon' => 'skull',
            ],
            [
                'name' => 'Master of Disguise',
                'type' => 'bump_dice_face',
                'config' => null,
                'available_at_level' => 5,
                'character_id' => $meredith,
                'max_selections' => 0,
                'sort_order' => 13,
                'description' => 'Become anyone, anywhere. +1 to a die face.',
                'icon' => 'dice',
            ],
            [
                'name' => 'Assassin\'s Mark',
                'type' => 'bump_two_dice_faces',
                'config' => null,
                'available_at_level' => 5,
                'character_id' => $meredith,
                'max_selections' => 2,
                'sort_order' => 21,
                'description' => 'Strike twice from the shadows. +1 to two die faces.',
                'icon' => 'dice-multiple',
            ],
            [
                'name' => 'Ghost Walk',
                'type' => 'add_wild',
                'config' => null,
                'available_at_level' => 6,
                'character_id' => $meredith,
                'max_selections' => 1,
                'sort_order' => 60,
                'description' => 'Vanish and reappear where least expected. Replace a die face with WILD.',
                'icon' => 'star',
            ],
            [
                'name' => 'Blackmail Dossier',
                'type' => 'passive_stat_bonus',
                'config' => ['stat' => 'wealth', 'value' => 1],
                'available_at_level' => 3,
                'character_id' => $meredith,
                'max_selections' => 1,
                'sort_order' => 52,
                'description' => 'Everyone has a price when you know their secrets. Start with +1 Wealth.',
                'icon' => 'coins',
            ],
            [
                'name' => 'Escape Route',
                'type' => 'card_redraw',
                'config' => null,
                'available_at_level' => 5,
                'character_id' => $meredith,
                'max_selections' => 1,
                'sort_order' => 71,
                'description' => 'Always have a way out. Redraw a card once per game.',
                'icon' => 'eye',
            ],
            [
                'name' => 'Safe House',
                'type' => 'extra_item_slot',
                'config' => null,
                'available_at_level' => 6,
                'character_id' => $meredith,
                'max_selections' => 2,
                'sort_order' => 41,
                'description' => 'Maintain hidden caches across the kingdom. +1 item slot.',
                'icon' => 'bag',
            ],

            // =============================================
            // GODWIN THE SAGE — The Scholar
            // =============================================
            [
                'name' => 'Careful Study',
                'type' => 'bump_dice_face',
                'config' => null,
                'available_at_level' => 1,
                'character_id' => $godwin,
                'max_selections' => 0,
                'sort_order' => 10,
                'description' => 'Methodical analysis yields better results. +1 to a die face.',
                'icon' => 'dice',
            ],
            [
                'name' => 'Library Access',
                'type' => 'passive_stat_bonus',
                'config' => ['stat' => 'influence', 'value' => 1],
                'available_at_level' => 1,
                'character_id' => $godwin,
                'max_selections' => 1,
                'sort_order' => 50,
                'description' => 'Knowledge is the truest form of power. Start with +1 Influence.',
                'icon' => 'crown',
            ],
            [
                'name' => 'Herbal Remedies',
                'type' => 'passive_stat_bonus',
                'config' => ['stat' => 'food', 'value' => 1],
                'available_at_level' => 1,
                'character_id' => $godwin,
                'max_selections' => 1,
                'sort_order' => 51,
                'description' => 'Botanical knowledge keeps the people healthy. Start with +1 Food.',
                'icon' => 'wheat',
            ],
            [
                'name' => 'Research Notes',
                'type' => 'bump_dice_face',
                'config' => null,
                'available_at_level' => 2,
                'character_id' => $godwin,
                'max_selections' => 0,
                'sort_order' => 11,
                'description' => 'Meticulous notes improve every endeavour. +1 to a die face.',
                'icon' => 'dice',
            ],
            [
                'name' => 'Scholar\'s Pack',
                'type' => 'start_with_item',
                'config' => ['random' => true],
                'available_at_level' => 2,
                'character_id' => $godwin,
                'max_selections' => 1,
                'sort_order' => 30,
                'description' => 'A well-stocked travelling laboratory. Start with a random item.',
                'icon' => 'backpack',
            ],
            [
                'name' => 'Expanded Archive',
                'type' => 'extra_item_slot',
                'config' => null,
                'available_at_level' => 3,
                'character_id' => $godwin,
                'max_selections' => 2,
                'sort_order' => 40,
                'description' => 'More storage for books, scrolls, and supplies. +1 item slot.',
                'icon' => 'bag',
            ],
            [
                'name' => 'Dual Thesis',
                'type' => 'bump_two_dice_faces',
                'config' => null,
                'available_at_level' => 3,
                'character_id' => $godwin,
                'max_selections' => 2,
                'sort_order' => 20,
                'description' => 'Apply two theories simultaneously. +1 to two die faces.',
                'icon' => 'dice-multiple',
            ],
            [
                'name' => 'Peer Review',
                'type' => 'card_redraw',
                'config' => null,
                'available_at_level' => 4,
                'character_id' => $godwin,
                'max_selections' => 1,
                'sort_order' => 70,
                'description' => 'Reconsider your approach with fresh eyes. Redraw a card once per game.',
                'icon' => 'eye',
            ],
            [
                'name' => 'Alchemical Mastery',
                'type' => 'bump_dice_face',
                'config' => null,
                'available_at_level' => 4,
                'character_id' => $godwin,
                'max_selections' => 0,
                'sort_order' => 12,
                'description' => 'Transmute failure into success. +1 to a die face.',
                'icon' => 'dice',
            ],
            [
                'name' => 'Forbidden Knowledge',
                'type' => 'start_with_curse',
                'config' => ['random' => true],
                'available_at_level' => 5,
                'character_id' => $godwin,
                'max_selections' => 1,
                'sort_order' => 80,
                'description' => 'Some truths come at a terrible price. Start each game with a random curse.',
                'icon' => 'skull',
            ],
            [
                'name' => 'Calculated Risk',
                'type' => 'bump_dice_face',
                'config' => null,
                'available_at_level' => 5,
                'character_id' => $godwin,
                'max_selections' => 0,
                'sort_order' => 13,
                'description' => 'Every variable accounted for. +1 to a die face.',
                'icon' => 'dice',
            ],
            [
                'name' => 'Unified Theory',
                'type' => 'bump_two_dice_faces',
                'config' => null,
                'available_at_level' => 5,
                'character_id' => $godwin,
                'max_selections' => 2,
                'sort_order' => 21,
                'description' => 'All knowledge converges into mastery. +1 to two die faces.',
                'icon' => 'dice-multiple',
            ],
            [
                'name' => 'Eureka Moment',
                'type' => 'add_wild',
                'config' => null,
                'available_at_level' => 6,
                'character_id' => $godwin,
                'max_selections' => 1,
                'sort_order' => 60,
                'description' => 'A flash of pure brilliance transcends all limits. Replace a die face with WILD.',
                'icon' => 'star',
            ],
            [
                'name' => 'Defensive Wards',
                'type' => 'passive_stat_bonus',
                'config' => ['stat' => 'security', 'value' => 1],
                'available_at_level' => 3,
                'character_id' => $godwin,
                'max_selections' => 1,
                'sort_order' => 52,
                'description' => 'Arcane protections shield the kingdom. Start with +1 Security.',
                'icon' => 'shield',
            ],
            [
                'name' => 'Ancient Texts',
                'type' => 'card_redraw',
                'config' => null,
                'available_at_level' => 5,
                'character_id' => $godwin,
                'max_selections' => 1,
                'sort_order' => 71,
                'description' => 'Forgotten wisdom guides your decisions. Redraw a card once per game.',
                'icon' => 'eye',
            ],
            [
                'name' => 'Patron of Arts',
                'type' => 'passive_stat_bonus',
                'config' => ['stat' => 'happiness', 'value' => 1],
                'available_at_level' => 4,
                'character_id' => $godwin,
                'max_selections' => 1,
                'sort_order' => 53,
                'description' => 'Your scholarship enriches the culture. Start with +1 Happiness.',
                'icon' => 'smile',
            ],
        ];

        foreach ($options as $option) {
            CharacterLevelOption::updateOrCreate(
                ['name' => $option['name'], 'character_id' => $option['character_id']],
                $option
            );
        }
    }
}