<?php

namespace Database\Seeders;

use App\Models\Card;
use App\Models\Character;
use App\Models\Event;
use Illuminate\Database\Seeder;

class GameContentSeeder extends Seeder
{
    public function run(): void
    {
        $this->seedCharacters();
        $this->seedCards();
        $this->seedEvents();
    }

    private function seedCharacters(): void
    {
        Character::truncate();

        $characters = [
            [
                'name' => 'Lord Reginald',
                'description' => 'A nobleman whose greatest talent is looking important while doing absolutely nothing. Has survived three coups by being too boring to assassinate.',
                'dice' => [
                    [3, 3, 4, 2, 2, 'WILD'],
                    [3, 3, 4, 2, 2, 3],
                    [3, 3, 4, 2, 2, 3],
                ],
                'wild_value' => 3,
                'wild_ability' => 'inspire',
                'wild_ability_description' => '+1 to total roll per player in the game',
            ],
            [
                'name' => 'Dame Ironside',
                'description' => 'A knight who once headbutted a battering ram and won. She solves most diplomatic problems by threatening to solve them violently.',
                'dice' => [
                    [4, 4, 3, 1, 1, 'WILD'],
                    [4, 4, 3, 1, 1, 3],
                    [4, 4, 3, 1, 1, 3],
                ],
                'wild_value' => 2,
                'wild_ability' => 'rally',
                'wild_ability_description' => 'Reroll the lowest die for a better result',
            ],
            [
                'name' => 'Brother Ambrose',
                'description' => 'A monk who claims to hear the voice of God. God mostly tells him to drink communion wine and avoid manual labor.',
                'dice' => [
                    [2, 3, 3, 2, 3, 'WILD'],
                    [2, 3, 3, 2, 3, 3],
                    [2, 3, 3, 2, 3, 3],
                ],
                'wild_value' => 4,
                'wild_ability' => 'divine',
                'wild_ability_description' => 'WILD counts as double its value',
            ],
            [
                'name' => 'Margery the Coinbiter',
                'description' => 'A merchant who can smell a bad deal from three counties away. Rumored to have once sold the same horse to five different buyers in one afternoon.',
                'dice' => [
                    [5, 5, 3, 1, 1, 'WILD'],
                    [5, 5, 3, 1, 1, 3],
                    [5, 5, 3, 1, 1, 3],
                ],
                'wild_value' => 3,
                'wild_ability' => 'gamble',
                'wild_ability_description' => 'Reroll all dice for a potentially bigger payoff',
            ],
            [
                'name' => 'Whisper',
                'description' => 'Nobody knows her real name. Nobody knows where she came from. She once stole the crown jewels, returned them, and left a thank-you note.',
                'dice' => [
                    [3, 3, 2, 2, 4, 'WILD'],
                    [3, 3, 2, 2, 4, 3],
                    [3, 3, 2, 2, 4, 3],
                ],
                'wild_value' => 3,
                'wild_ability' => 'shadow',
                'wild_ability_description' => 'Peek at upcoming cards',
            ],
            [
                'name' => 'Old Godwin',
                'description' => 'The kingdom\'s oldest living advisor. Has outlasted seven kings and remembers when the castle was just a "nice pile of rocks." Falls asleep mid-sentence but his snoring sounds like wisdom.',
                'dice' => [
                    [2, 2, 3, 3, 2, 'WILD'],
                    [2, 2, 3, 3, 2, 2],
                    [2, 2, 3, 3, 2, 2],
                ],
                'wild_value' => 5,
                'wild_ability' => 'wisdom',
                'wild_ability_description' => '+2 to the total roll',
            ],
        ];

        foreach ($characters as $character) {
            Character::create($character);
        }
    }

    private function seedCards(): void
    {
        Card::truncate();

        $order = 1;
        $cards = [
            // =============================================
            // MILITARY (~25 cards)
            // =============================================
            [
                'title' => 'The Peasant Uprising',
                'description' => 'Angry farmers are marching toward the castle with pitchforks. One of them has a strongly-worded letter.',
                'difficulty' => 5,
                'positive_effects' => ['security' => 3, 'happiness' => 2],
                'negative_effects' => ['happiness' => -2],
                'positive_flavor' => 'You address their grievances. The letter was actually quite reasonable.',
                'negative_flavor' => 'They set fire to a haystack in protest. It was their own haystack.',
                'category' => 'military',
            ],
            [
                'title' => 'Knight Tryouts',
                'description' => 'Dozens of would-be knights have shown up to prove their worth. One brought his mum.',
                'difficulty' => 4,
                'positive_effects' => ['security' => 3, 'influence' => 1],
                'negative_effects' => ['security' => -1],
                'positive_flavor' => 'You recruit several capable fighters. The one with his mum was actually the best.',
                'negative_flavor' => 'Most of them can\'t tell which end of the sword to hold.',
                'category' => 'military',
            ],
            [
                'title' => 'The Siege Next Door',
                'description' => 'Your neighbor\'s castle is being besieged. He\'s sent a raven asking if you could keep the noise down.',
                'difficulty' => 7,
                'positive_effects' => ['security' => 4, 'influence' => 3],
                'negative_effects' => ['security' => -2, 'wealth' => -1],
                'positive_flavor' => 'Your army lifts the siege. Your neighbor promises to return the lawn mower.',
                'negative_flavor' => 'The invaders redirect their attention to your considerably nicer castle.',
                'category' => 'military',
            ],
            [
                'title' => 'Suspicious Tunneling',
                'description' => 'Guards report strange digging sounds beneath the castle walls. Could be sappers. Could be badgers.',
                'difficulty' => 6,
                'positive_effects' => ['security' => 4],
                'negative_effects' => ['security' => -2],
                'positive_flavor' => 'It was sappers. You collapse the tunnel and capture them. They confess everything.',
                'negative_flavor' => 'It was sappers AND badgers. The badgers were a distraction. Clever.',
                'category' => 'military',
            ],
            [
                'title' => 'The Duel',
                'description' => 'A foreign knight challenges your champion to single combat. Your champion is currently on his lunch break.',
                'difficulty' => 8,
                'positive_effects' => ['security' => 3, 'influence' => 4],
                'negative_effects' => ['influence' => -3],
                'positive_flavor' => 'Your champion finishes his sandwich, then finishes the duel. Magnificent.',
                'negative_flavor' => 'He shouldn\'t have had that second helping. Defeat by food coma.',
                'category' => 'military',
            ],
            [
                'title' => 'Arrow Shortage',
                'description' => 'The archers have run out of arrows. They\'ve been throwing insults instead, but it\'s less effective.',
                'difficulty' => 4,
                'positive_effects' => ['security' => 3],
                'negative_effects' => ['security' => -1, 'wealth' => -1],
                'positive_flavor' => 'New arrows are forged. The insults continue anyway, for morale.',
                'negative_flavor' => 'The archers resort to throwing rocks. It\'s very undignified.',
                'category' => 'military',
            ],
            [
                'title' => 'Mercenary Offer',
                'description' => 'A band of sellswords offers their services. Their references include "probably won\'t betray you."',
                'difficulty' => 6,
                'positive_effects' => ['security' => 4, 'influence' => 1],
                'negative_effects' => ['wealth' => -2],
                'positive_flavor' => 'They\'re surprisingly professional. One even brought his own tent.',
                'negative_flavor' => 'They take the gold and leave. Their "references" were fictional.',
                'category' => 'military',
            ],
            [
                'title' => 'Castle Repairs',
                'description' => 'The east wall is crumbling. The mason says it\'ll hold "probably" and "depends on the weather."',
                'difficulty' => 5,
                'positive_effects' => ['security' => 4],
                'negative_effects' => ['security' => -2],
                'positive_flavor' => 'The wall is reinforced and now features decorative crenellations. Very chic.',
                'negative_flavor' => 'A particularly assertive gust of wind brings down half the battlement.',
                'category' => 'military',
            ],
            [
                'title' => 'Viking Raid',
                'description' => 'Longships on the horizon! The Vikings are here, and they haven\'t come for the weather.',
                'difficulty' => 9,
                'positive_effects' => ['security' => 5, 'influence' => 3],
                'negative_effects' => ['security' => -3, 'food' => -2],
                'positive_flavor' => 'Your coastal defenses hold! The Vikings sail away, cursing in Norse.',
                'negative_flavor' => 'They pillage the seaside villages and take all the good ale.',
                'category' => 'military',
            ],
            [
                'title' => 'Guard Napping',
                'description' => 'The night watch has been caught sleeping on duty. In their defense, it was very late.',
                'difficulty' => 3,
                'positive_effects' => ['security' => 2, 'happiness' => 1],
                'negative_effects' => ['security' => -1],
                'positive_flavor' => 'New shift rotations are introduced. Guards are now only mostly asleep.',
                'negative_flavor' => 'Someone sneaks past and draws a mustache on the royal portrait.',
                'category' => 'military',
            ],
            [
                'title' => 'Dragon Sighting',
                'description' => 'A farmer claims to have seen a dragon. Investigation reveals it was a very large, very angry goose.',
                'difficulty' => 4,
                'positive_effects' => ['security' => 2, 'happiness' => 2],
                'negative_effects' => ['happiness' => -1],
                'positive_flavor' => 'The goose is captured and donated to the royal menagerie. Morale improves.',
                'negative_flavor' => 'The goose escapes and terrorizes the market square. Fear spreads.',
                'category' => 'military',
            ],
            [
                'title' => 'Border Dispute',
                'description' => 'Two lords are fighting over a fence that\'s apparently six inches too far to the left.',
                'difficulty' => 5,
                'positive_effects' => ['influence' => 3, 'security' => 2],
                'negative_effects' => ['influence' => -2],
                'positive_flavor' => 'You mediate brilliantly. The fence moves three inches. Both lords claim victory.',
                'negative_flavor' => 'Both lords raise armies over the fence. This is why we can\'t have nice things.',
                'category' => 'military',
            ],
            [
                'title' => 'Catapult Testing',
                'description' => 'The engineers want to test the new siege engine. They\'ve loaded it with a watermelon for safety.',
                'difficulty' => 5,
                'positive_effects' => ['security' => 3, 'happiness' => 1],
                'negative_effects' => ['happiness' => -1],
                'positive_flavor' => 'The watermelon sails gracefully across the field. The crowd cheers.',
                'negative_flavor' => 'The catapult misfires into the Great Hall. Watermelon everywhere.',
                'category' => 'military',
            ],
            [
                'title' => 'Moat Renovation',
                'description' => 'The moat has become more of a "decorative ditch." The crocodiles have left for a castle with better amenities.',
                'difficulty' => 6,
                'positive_effects' => ['security' => 4],
                'negative_effects' => ['wealth' => -2],
                'positive_flavor' => 'The moat is restored to its former glory. The crocodiles send a raven expressing interest in returning.',
                'negative_flavor' => 'Funds run out halfway. You now have half a moat, which is worse than no moat.',
                'category' => 'military',
            ],
            [
                'title' => 'War Elephant',
                'description' => 'A traveling merchant offers to sell you a war elephant. It\'s "slightly used" and "house-trained."',
                'difficulty' => 7,
                'positive_effects' => ['security' => 5, 'influence' => 2],
                'negative_effects' => ['food' => -3],
                'positive_flavor' => 'The elephant is magnificent and terrifies your enemies. Worth every turnip.',
                'negative_flavor' => 'It eats the entire grain reserves in three days. The merchant has fled the country.',
                'category' => 'military',
            ],
            [
                'title' => 'Scouts Report',
                'description' => 'Your scouts report enemy movement in the eastern woods. Or possibly a very large picnic.',
                'difficulty' => 5,
                'positive_effects' => ['security' => 3, 'influence' => 1],
                'negative_effects' => ['security' => -1],
                'positive_flavor' => 'It was an invasion force. Your early warning saves the kingdom.',
                'negative_flavor' => 'It was actually a picnic. You\'ve mobilized the army for nothing. Awkward.',
                'category' => 'military',
            ],
            [
                'title' => 'Deserters',
                'description' => 'A dozen soldiers have abandoned their posts. Their excuse: "We thought the war was over."',
                'difficulty' => 6,
                'positive_effects' => ['security' => 3, 'influence' => 2],
                'negative_effects' => ['security' => -2],
                'positive_flavor' => 'They\'re found at a tavern and brought back. Discipline is restored with a stern lecture.',
                'negative_flavor' => 'Others follow their example. The border guard is now one man and a dog.',
                'category' => 'military',
            ],
            [
                'title' => 'The Battering Ram',
                'description' => 'Your engineers have built a battering ram. They named it "Gerald."',
                'difficulty' => 4,
                'positive_effects' => ['security' => 3],
                'negative_effects' => ['wealth' => -1],
                'positive_flavor' => 'Gerald performs admirably in testing. The engineers are very proud.',
                'negative_flavor' => 'Gerald falls apart on the first swing. The engineers blame the wood.',
                'category' => 'military',
            ],
            [
                'title' => 'Shield Wall Practice',
                'description' => 'The soldiers need training. Currently their shield wall looks more like a shield suggestion.',
                'difficulty' => 4,
                'positive_effects' => ['security' => 3, 'happiness' => 1],
                'negative_effects' => ['happiness' => -1],
                'positive_flavor' => 'After weeks of drilling, the shield wall is impenetrable. Very satisfying.',
                'negative_flavor' => 'Three broken noses and a concussion. The wall still has gaps.',
                'category' => 'military',
            ],
            [
                'title' => 'Secret Passage',
                'description' => 'A hidden tunnel has been discovered beneath the castle. It leads to either an escape route or the wine cellar.',
                'difficulty' => 5,
                'positive_effects' => ['security' => 3, 'happiness' => 2],
                'negative_effects' => ['security' => -2],
                'positive_flavor' => 'It leads to both! Strategic AND delicious.',
                'negative_flavor' => 'Enemies have been using it to steal your best vintages for months.',
                'category' => 'military',
            ],

            // =============================================
            // POLITICAL (~25 cards)
            // =============================================
            [
                'title' => 'Royal Wedding',
                'description' => 'A political marriage has been proposed. The bride is lovely. The groom is a duchy with excellent farmland.',
                'difficulty' => 6,
                'positive_effects' => ['influence' => 4, 'happiness' => 2],
                'negative_effects' => ['influence' => -2],
                'positive_flavor' => 'The wedding is a tremendous success. The cake alone weighs more than the bride.',
                'negative_flavor' => 'The groom objects to being treated like real estate. Diplomacy collapses.',
                'category' => 'political',
            ],
            [
                'title' => 'The Ambassador',
                'description' => 'The French ambassador has arrived. He\'s already complained about the food, the weather, and the tapestries.',
                'difficulty' => 7,
                'positive_effects' => ['influence' => 4, 'wealth' => 2],
                'negative_effects' => ['influence' => -2, 'happiness' => -1],
                'positive_flavor' => 'A trade deal is struck. He admits the cheese is "acceptable."',
                'negative_flavor' => 'He leaves in a huff and writes unflattering poems about your castle.',
                'category' => 'political',
            ],
            [
                'title' => 'Succession Crisis',
                'description' => 'The King\'s nephew and the King\'s niece both claim the throne. The King is very much still alive and confused.',
                'difficulty' => 8,
                'positive_effects' => ['influence' => 5, 'security' => 2],
                'negative_effects' => ['influence' => -3, 'security' => -1],
                'positive_flavor' => 'You convince them to wait until the King actually dies. Revolutionary diplomacy.',
                'negative_flavor' => 'They split the court into factions. Dinner parties become very tense.',
                'category' => 'political',
            ],
            [
                'title' => 'Tax Collectors',
                'description' => 'The tax collectors are deeply unpopular. One was pelted with turnips yesterday. He kept the turnips.',
                'difficulty' => 5,
                'positive_effects' => ['wealth' => 3, 'influence' => 1],
                'negative_effects' => ['happiness' => -2],
                'positive_flavor' => 'Taxes are collected with minimal vegetable-based violence.',
                'negative_flavor' => 'A full-scale turnip riot erupts. The collectors flee.',
                'category' => 'political',
            ],
            [
                'title' => 'Council Meeting',
                'description' => 'The lords are arguing again. Lord Pemberton insists on speaking in the third person.',
                'difficulty' => 5,
                'positive_effects' => ['influence' => 3, 'happiness' => 1],
                'negative_effects' => ['influence' => -1],
                'positive_flavor' => 'A consensus is reached. Lord Pemberton is pleased. Lord Pemberton always is.',
                'negative_flavor' => 'The meeting devolves into shouting. Lord Pemberton leaves in Lord Pemberton\'s carriage.',
                'category' => 'political',
            ],
            [
                'title' => 'Royal Decree',
                'description' => 'You must issue a proclamation. The scribe is ready, but he spells "decree" with three E\'s.',
                'difficulty' => 4,
                'positive_effects' => ['influence' => 3, 'happiness' => 1],
                'negative_effects' => ['influence' => -1],
                'positive_flavor' => 'The decree is well-received. Nobody notices the spelling.',
                'negative_flavor' => 'The poorly-worded decree accidentally outlaws Tuesdays.',
                'category' => 'political',
            ],
            [
                'title' => 'Spy in Court',
                'description' => 'Someone in the court is leaking secrets. Suspicion falls on the man who keeps taking notes and looking shifty.',
                'difficulty' => 7,
                'positive_effects' => ['influence' => 4, 'security' => 2],
                'negative_effects' => ['influence' => -2, 'security' => -1],
                'positive_flavor' => 'The spy is caught. He was actually a novelist researching his next book.',
                'negative_flavor' => 'Your battle plans appear in a rival kingdom\'s newsletter.',
                'category' => 'political',
            ],
            [
                'title' => 'The Petition',
                'description' => 'A peasant has traveled three days to present a petition. It\'s a complaint about his neighbor\'s rooster.',
                'difficulty' => 3,
                'positive_effects' => ['happiness' => 3, 'influence' => 1],
                'negative_effects' => ['happiness' => -1],
                'positive_flavor' => 'You resolve the rooster dispute with Solomonic wisdom. The peasant weeps with gratitude.',
                'negative_flavor' => 'You dismiss him. Word spreads that the crown doesn\'t care about roosters.',
                'category' => 'political',
            ],
            [
                'title' => 'Treaty Negotiations',
                'description' => 'Peace talks with the Scots. They\'ve brought whisky. This could go either way.',
                'difficulty' => 8,
                'positive_effects' => ['influence' => 5, 'security' => 3],
                'negative_effects' => ['influence' => -3],
                'positive_flavor' => 'A peace treaty is signed! Nobody can remember the details, but everyone agreed.',
                'negative_flavor' => 'Negotiations break down after an argument about whose country has better weather.',
                'category' => 'political',
            ],
            [
                'title' => 'The Heir\'s Tutor',
                'description' => 'The young prince needs an education. Applications include a monk, a philosopher, and a traveling circus performer.',
                'difficulty' => 5,
                'positive_effects' => ['influence' => 3, 'happiness' => 2],
                'negative_effects' => ['influence' => -2],
                'positive_flavor' => 'The prince becomes remarkably well-educated. He can juggle AND recite Latin.',
                'negative_flavor' => 'The prince learns nothing of statecraft but can do an excellent backflip.',
                'category' => 'political',
            ],
            [
                'title' => 'Feudal Complaint',
                'description' => 'A vassal lord has submitted a 47-page grievance. It\'s mostly about hedgerow boundaries.',
                'difficulty' => 4,
                'positive_effects' => ['influence' => 2, 'happiness' => 2],
                'negative_effects' => ['influence' => -1],
                'positive_flavor' => 'You read all 47 pages. The lord is so impressed he swears eternal loyalty.',
                'negative_flavor' => 'You use the document as kindling. The lord raises an army over hedgerows.',
                'category' => 'political',
            ],
            [
                'title' => 'Coronation Anniversary',
                'description' => 'The kingdom celebrates another year of not collapsing. Festivities are expected.',
                'difficulty' => 5,
                'positive_effects' => ['happiness' => 4, 'influence' => 2],
                'negative_effects' => ['wealth' => -2],
                'positive_flavor' => 'A grand celebration! The jousting tournament only results in minor injuries.',
                'negative_flavor' => 'The fireworks set the royal tent on fire. Festive, in a way.',
                'category' => 'political',
            ],
            [
                'title' => 'Noble Scandal',
                'description' => 'A prominent lord has been caught in a compromising situation involving a goat and a bucket of cream.',
                'difficulty' => 6,
                'positive_effects' => ['influence' => 3, 'happiness' => 2],
                'negative_effects' => ['influence' => -2],
                'positive_flavor' => 'You handle the scandal with discretion. The lord owes you a massive favor.',
                'negative_flavor' => 'The scandal spreads. Ballads are already being written. Very catchy ones.',
                'category' => 'political',
            ],
            [
                'title' => 'Foreign Dignitary',
                'description' => 'A visiting dignitary from the East brings exotic gifts and an entourage of 200. Your guest rooms hold 12.',
                'difficulty' => 6,
                'positive_effects' => ['influence' => 4, 'wealth' => 2],
                'negative_effects' => ['wealth' => -2, 'food' => -1],
                'positive_flavor' => 'The visit cements a lucrative trade alliance. The gifts include actual spices!',
                'negative_flavor' => 'The 200-person entourage eats you out of house and home. Literally.',
                'category' => 'political',
            ],
            [
                'title' => 'Election of the Sheriff',
                'description' => 'The shire needs a new sheriff. Candidates include a retired knight and the village drunk (surprisingly popular).',
                'difficulty' => 4,
                'positive_effects' => ['influence' => 3, 'security' => 1],
                'negative_effects' => ['happiness' => -1],
                'positive_flavor' => 'The retired knight brings order. Crime drops. Tavern attendance also drops.',
                'negative_flavor' => 'The village drunk wins by a landslide. Law enforcement takes a creative turn.',
                'category' => 'political',
            ],
            [
                'title' => 'The Census',
                'description' => 'Time to count the peasants. The peasants are not enthusiastic about being counted.',
                'difficulty' => 5,
                'positive_effects' => ['influence' => 3, 'wealth' => 2],
                'negative_effects' => ['happiness' => -2],
                'positive_flavor' => 'The census reveals the kingdom is larger than anyone thought. More taxpayers!',
                'negative_flavor' => 'Half the peasants hide in the woods until the census-takers leave.',
                'category' => 'political',
            ],
            [
                'title' => 'Court Jester Crisis',
                'description' => 'The court jester has accidentally insulted the visiting duke. His joke about "noble gases" went over poorly.',
                'difficulty' => 4,
                'positive_effects' => ['happiness' => 3, 'influence' => 1],
                'negative_effects' => ['influence' => -2],
                'positive_flavor' => 'The duke eventually laughs. The jester lives another day.',
                'negative_flavor' => 'The duke demands the jester\'s hat. The jester is devastated without it.',
                'category' => 'political',
            ],
            [
                'title' => 'Magna Carta Draft',
                'description' => 'The barons want to limit your power. They\'ve written it down and everything.',
                'difficulty' => 9,
                'positive_effects' => ['influence' => 5, 'happiness' => 3],
                'negative_effects' => ['influence' => -4],
                'positive_flavor' => 'You negotiate reasonable terms. History will remember this fondly.',
                'negative_flavor' => 'You refuse. The barons are cross. Very, very cross.',
                'category' => 'political',
            ],
            [
                'title' => 'Royal Portrait',
                'description' => 'A painter offers to capture your likeness for posterity. He promises to "work with what he has."',
                'difficulty' => 3,
                'positive_effects' => ['influence' => 2, 'happiness' => 2],
                'negative_effects' => ['happiness' => -1],
                'positive_flavor' => 'The portrait is magnificent. You look 20 years younger and a foot taller.',
                'negative_flavor' => 'The portrait is "honest." You look like a startled potato.',
                'category' => 'political',
            ],
            [
                'title' => 'Hostage Exchange',
                'description' => 'A neighboring kingdom offers to return your cousin in exchange for their duke. Your cousin is... fine.',
                'difficulty' => 6,
                'positive_effects' => ['influence' => 3, 'security' => 2],
                'negative_effects' => ['influence' => -2],
                'positive_flavor' => 'The exchange goes smoothly. Your cousin has actually enjoyed the holiday.',
                'negative_flavor' => 'The deal falls apart. Your cousin writes to say he\'d rather stay where he is.',
                'category' => 'political',
            ],

            // =============================================
            // RELIGIOUS (~20 cards)
            // =============================================
            [
                'title' => 'Holy Relic',
                'description' => 'A merchant claims to sell a genuine holy relic: the left sock of Saint Bartholomew.',
                'difficulty' => 5,
                'positive_effects' => ['religion' => 4, 'happiness' => 1],
                'negative_effects' => ['religion' => -1, 'wealth' => -1],
                'positive_flavor' => 'The sock performs a minor miracle. Pilgrims flock to see it.',
                'negative_flavor' => 'It\'s just a sock. An old, regular sock. The pilgrims want refunds.',
                'category' => 'religious',
            ],
            [
                'title' => 'Church Roof',
                'description' => 'The cathedral roof is leaking again. The bishop says God is testing them. The mason says it\'s the gutters.',
                'difficulty' => 4,
                'positive_effects' => ['religion' => 3, 'happiness' => 1],
                'negative_effects' => ['religion' => -1],
                'positive_flavor' => 'The roof is fixed. Services resume without umbrellas.',
                'negative_flavor' => 'It rains during mass. The bishop claims it\'s holy water now.',
                'category' => 'religious',
            ],
            [
                'title' => 'The Hermit',
                'description' => 'A holy hermit has emerged from 20 years of solitude. He\'d like to know if you\'ve heard the good news.',
                'difficulty' => 4,
                'positive_effects' => ['religion' => 3, 'happiness' => 2],
                'negative_effects' => ['happiness' => -1],
                'positive_flavor' => 'The hermit\'s wisdom draws crowds. He\'s the most popular person nobody has met.',
                'negative_flavor' => 'He won\'t stop talking. Twenty years of silence created a backlog.',
                'category' => 'religious',
            ],
            [
                'title' => 'Witch Trial',
                'description' => 'A woman has been accused of witchcraft. Evidence: she has a cat and is "a bit odd."',
                'difficulty' => 7,
                'positive_effects' => ['religion' => 3, 'influence' => 2],
                'negative_effects' => ['happiness' => -3, 'religion' => -1],
                'positive_flavor' => 'You declare her innocent. She\'s just a woman with a cat. The crowd accepts it.',
                'negative_flavor' => 'The trial becomes a spectacle. Half the kingdom is now suspicious of cat owners.',
                'category' => 'religious',
            ],
            [
                'title' => 'Papal Envoy',
                'description' => 'An envoy from Rome arrives bearing a letter from the Pope. It\'s mostly asking for money.',
                'difficulty' => 6,
                'positive_effects' => ['religion' => 4, 'influence' => 2],
                'negative_effects' => ['wealth' => -2, 'religion' => -1],
                'positive_flavor' => 'You make a generous donation. The Pope sends a blessed thank-you card.',
                'negative_flavor' => 'You decline. The envoy makes pointed comments about your "spiritual health."',
                'category' => 'religious',
            ],
            [
                'title' => 'Monastery Brew',
                'description' => 'The monks have perfected a new ale recipe. It\'s incredibly popular. Attendance at vespers has tripled.',
                'difficulty' => 3,
                'positive_effects' => ['religion' => 2, 'happiness' => 3],
                'negative_effects' => ['religion' => -1],
                'positive_flavor' => 'The ale is blessed and sold throughout the kingdom. Everyone is happy and slightly tipsy.',
                'negative_flavor' => 'The monks drink most of it themselves. Matins becomes very loud.',
                'category' => 'religious',
            ],
            [
                'title' => 'Pilgrimage Route',
                'description' => 'A new pilgrimage route passes through your kingdom. Pilgrims bring coins and leave behind... enthusiasm.',
                'difficulty' => 5,
                'positive_effects' => ['religion' => 3, 'wealth' => 2],
                'negative_effects' => ['food' => -1],
                'positive_flavor' => 'The pilgrimage route brings prosperity and an annoying number of souvenir sellers.',
                'negative_flavor' => 'The pilgrims trample the crops. God works in mysterious and agricultural ways.',
                'category' => 'religious',
            ],
            [
                'title' => 'Miracle Claims',
                'description' => 'A local well is reportedly curing baldness. The queue stretches half a mile.',
                'difficulty' => 4,
                'positive_effects' => ['religion' => 3, 'happiness' => 2],
                'negative_effects' => ['religion' => -2],
                'positive_flavor' => 'The well becomes a famous shrine. Hair-related miracles are surprisingly popular.',
                'negative_flavor' => 'The well was contaminated by a tannery upstream. Not a miracle.',
                'category' => 'religious',
            ],
            [
                'title' => 'Heresy Accusations',
                'description' => 'The bishop accuses the local philosopher of heresy. The philosopher\'s crime: asking too many questions.',
                'difficulty' => 7,
                'positive_effects' => ['religion' => 3, 'influence' => 3],
                'negative_effects' => ['religion' => -2, 'happiness' => -1],
                'positive_flavor' => 'You protect the philosopher. Free thought flourishes, carefully.',
                'negative_flavor' => 'The philosopher is silenced. Everyone stops asking questions. Blissful ignorance.',
                'category' => 'religious',
            ],
            [
                'title' => 'Bell Tower',
                'description' => 'The church wants a bigger bell. The current one sounds "insufficiently majestic."',
                'difficulty' => 4,
                'positive_effects' => ['religion' => 3, 'happiness' => 1],
                'negative_effects' => ['wealth' => -1],
                'positive_flavor' => 'The new bell can be heard three counties away. Magnificent, if deafening.',
                'negative_flavor' => 'The old bell falls during removal and makes a very final sound.',
                'category' => 'religious',
            ],
            [
                'title' => 'Crusade Call',
                'description' => 'The Pope calls for a crusade. Your knights are keen. Your treasurer is having chest pains.',
                'difficulty' => 9,
                'positive_effects' => ['religion' => 5, 'influence' => 3],
                'negative_effects' => ['wealth' => -3, 'security' => -2],
                'positive_flavor' => 'Your knights return with glory, stories, and some very nice carpets.',
                'negative_flavor' => 'The crusade bankrupts the treasury. Your knights bring home only sunburn.',
                'category' => 'religious',
            ],
            [
                'title' => 'Saint\'s Day Feast',
                'description' => 'The feast of the patron saint approaches. The peasants expect time off. The lords expect productivity.',
                'difficulty' => 4,
                'positive_effects' => ['religion' => 2, 'happiness' => 3],
                'negative_effects' => ['wealth' => -1],
                'positive_flavor' => 'A grand feast is held. The patron saint would be proud, assuming saints eat pie.',
                'negative_flavor' => 'You cancel the feast. The peasants celebrate anyway, just more angrily.',
                'category' => 'religious',
            ],
            [
                'title' => 'Confession Booth',
                'description' => 'The priest reports that confessions have gotten "very interesting" lately. He looks concerned.',
                'difficulty' => 5,
                'positive_effects' => ['religion' => 3, 'security' => 1],
                'negative_effects' => ['happiness' => -1],
                'positive_flavor' => 'Confessions reveal a plot against the throne. God works in useful ways.',
                'negative_flavor' => 'The priest starts acting very nervous around everyone. Nobody knows why.',
                'category' => 'religious',
            ],
            [
                'title' => 'Monastery Expansion',
                'description' => 'The abbot wants to expand the monastery. His plans include a scriptorium, herb garden, and suspiciously elaborate wine cellar.',
                'difficulty' => 5,
                'positive_effects' => ['religion' => 4, 'influence' => 1],
                'negative_effects' => ['wealth' => -2],
                'positive_flavor' => 'The expanded monastery becomes a center of learning and excellent wine.',
                'negative_flavor' => 'Funds dry up mid-construction. The monks live in an elaborate ruin.',
                'category' => 'religious',
            ],
            [
                'title' => 'Excommunication Threat',
                'description' => 'The bishop threatens excommunication unless you do something about the "sinful dancing" at the village fair.',
                'difficulty' => 6,
                'positive_effects' => ['religion' => 4],
                'negative_effects' => ['happiness' => -3],
                'positive_flavor' => 'A compromise is reached: dancing is permitted but must look solemn.',
                'negative_flavor' => 'You ban dancing. The peasants revolt with aggressive morris dancing.',
                'category' => 'religious',
            ],

            // =============================================
            // ECONOMIC (~25 cards)
            // =============================================
            [
                'title' => 'Tax Season',
                'description' => 'The annual tax collection approaches. The peasants have already started hiding their chickens.',
                'difficulty' => 5,
                'positive_effects' => ['wealth' => 4, 'influence' => 1],
                'negative_effects' => ['happiness' => -2],
                'positive_flavor' => 'Taxes are collected successfully. Some chickens remain unaccounted for.',
                'negative_flavor' => 'A mass chicken migration is reported. The treasury remains light.',
                'category' => 'economic',
            ],
            [
                'title' => 'Trade Route',
                'description' => 'Merchants propose a new trade route. It passes through bandit territory, bear territory, and Gary\'s farm. Gary is worse than both.',
                'difficulty' => 6,
                'positive_effects' => ['wealth' => 4, 'influence' => 2],
                'negative_effects' => ['wealth' => -2],
                'positive_flavor' => 'The route is established. Gary is surprisingly cooperative once you meet his price.',
                'negative_flavor' => 'Bandits, bears, and Gary all demand tolls. The route is unprofitable.',
                'category' => 'economic',
            ],
            [
                'title' => 'Gold Mine',
                'description' => 'Prospectors claim to have found gold in the hills. They said the same thing last month about copper. It was dirt.',
                'difficulty' => 7,
                'positive_effects' => ['wealth' => 5, 'happiness' => 2],
                'negative_effects' => ['wealth' => -2],
                'positive_flavor' => 'It\'s actually gold! Not much, but enough to make the kingdom slightly less poor.',
                'negative_flavor' => 'It\'s pyrite. Fool\'s gold. The prospectors live up to their find.',
                'category' => 'economic',
            ],
            [
                'title' => 'Market Day',
                'description' => 'The weekly market is thriving, though someone is selling "artisanal mud" and charging three pence.',
                'difficulty' => 3,
                'positive_effects' => ['wealth' => 2, 'happiness' => 2],
                'negative_effects' => ['happiness' => -1],
                'positive_flavor' => 'The market prospers. The artisanal mud somehow sells out.',
                'negative_flavor' => 'A brawl breaks out over the last turnip. Market day is suspended.',
                'category' => 'economic',
            ],
            [
                'title' => 'Coin Clipping',
                'description' => 'Someone has been shaving the edges off coins. The kingdom\'s money is literally shrinking.',
                'difficulty' => 6,
                'positive_effects' => ['wealth' => 3, 'security' => 2],
                'negative_effects' => ['wealth' => -2],
                'positive_flavor' => 'The counterfeiter is caught. He had a very impressive coin collection.',
                'negative_flavor' => 'The coin-clipper remains at large. Coins are now suspiciously thin.',
                'category' => 'economic',
            ],
            [
                'title' => 'Harvest Festival',
                'description' => 'The harvest is in. Time to celebrate with ale, feasting, and competitive vegetable growing.',
                'difficulty' => 4,
                'positive_effects' => ['food' => 3, 'happiness' => 3],
                'negative_effects' => ['food' => -1],
                'positive_flavor' => 'A record harvest! The prize turnip weighs more than a small child.',
                'negative_flavor' => 'The harvest is meager. The prize turnip is the size of a walnut.',
                'category' => 'economic',
            ],
            [
                'title' => 'Foreign Traders',
                'description' => 'Venetian merchants arrive with silk, spices, and an air of superiority that could cut glass.',
                'difficulty' => 6,
                'positive_effects' => ['wealth' => 4, 'happiness' => 1],
                'negative_effects' => ['wealth' => -1],
                'positive_flavor' => 'Trade agreements are made. Your castle now smells of cinnamon.',
                'negative_flavor' => 'They sell you "exotic spices" that turn out to be colored sand.',
                'category' => 'economic',
            ],
            [
                'title' => 'Bridge Toll',
                'description' => 'The kingdom\'s only bridge needs maintenance. A toll is proposed. The peasants suggest the lords swim.',
                'difficulty' => 5,
                'positive_effects' => ['wealth' => 3, 'security' => 1],
                'negative_effects' => ['happiness' => -2],
                'positive_flavor' => 'The toll funds repairs and turns a tidy profit. The bridge has never looked better.',
                'negative_flavor' => 'Peasants build a raft to avoid the toll. Three drown. The bridge remains unfixed.',
                'category' => 'economic',
            ],
            [
                'title' => 'Royal Mint',
                'description' => 'Time to mint new coins. The design committee cannot agree on whose face to use.',
                'difficulty' => 5,
                'positive_effects' => ['wealth' => 4, 'influence' => 1],
                'negative_effects' => ['influence' => -1],
                'positive_flavor' => 'Beautiful new coins are minted. Your profile looks very regal from that angle.',
                'negative_flavor' => 'The coins are minted with a typo. You are now "King of Enlgand."',
                'category' => 'economic',
            ],
            [
                'title' => 'Wool Trade',
                'description' => 'English wool is in demand abroad. The sheep, however, are demanding better working conditions.',
                'difficulty' => 4,
                'positive_effects' => ['wealth' => 3, 'food' => 1],
                'negative_effects' => ['food' => -1],
                'positive_flavor' => 'Wool exports boom. The sheep remain blissfully unaware of economics.',
                'negative_flavor' => 'A sheep shortage leads to a wool crisis. Everyone is cold and cross.',
                'category' => 'economic',
            ],
            [
                'title' => 'Grain Storage',
                'description' => 'The granaries are full, but rats have been spotted. The castle cat is "on holiday."',
                'difficulty' => 4,
                'positive_effects' => ['food' => 4],
                'negative_effects' => ['food' => -2],
                'positive_flavor' => 'The cat returns from holiday and handles the situation professionally.',
                'negative_flavor' => 'The rats eat a third of the grain. The cat sends a postcard from France.',
                'category' => 'economic',
            ],
            [
                'title' => 'Guild Dispute',
                'description' => 'The bakers\' guild and the butchers\' guild are at war. Pies are caught in the crossfire.',
                'difficulty' => 5,
                'positive_effects' => ['wealth' => 2, 'happiness' => 3],
                'negative_effects' => ['happiness' => -2],
                'positive_flavor' => 'Peace is brokered. A new pie guild is formed to prevent future conflicts.',
                'negative_flavor' => 'The pie embargo continues. The kingdom suffers a devastating pie shortage.',
                'category' => 'economic',
            ],
            [
                'title' => 'Fishing Rights',
                'description' => 'Two villages are fighting over fishing rights to the river. The fish have no comment.',
                'difficulty' => 4,
                'positive_effects' => ['food' => 3, 'happiness' => 1],
                'negative_effects' => ['happiness' => -1],
                'positive_flavor' => 'Fishing rights are divided fairly. Fish stocks recover. Everyone gets their supper.',
                'negative_flavor' => 'Both villages overfish in protest. The river is now basically a puddle.',
                'category' => 'economic',
            ],
            [
                'title' => 'Debasement',
                'description' => 'Your treasurer suggests adding copper to the silver coins. "Nobody will notice," he assures you. He\'s sweating.',
                'difficulty' => 6,
                'positive_effects' => ['wealth' => 4],
                'negative_effects' => ['influence' => -2, 'wealth' => -1],
                'positive_flavor' => 'The subtle change goes unnoticed. The treasury breathes easier.',
                'negative_flavor' => 'Everyone notices. The coins turn green. Trust in the crown plummets.',
                'category' => 'economic',
            ],
            [
                'title' => 'Windmill Construction',
                'description' => 'Engineers propose building windmills. The local donkeys, currently grinding flour, seem relieved.',
                'difficulty' => 5,
                'positive_effects' => ['food' => 3, 'wealth' => 2],
                'negative_effects' => ['wealth' => -1],
                'positive_flavor' => 'The windmills are a triumph of engineering. The donkeys are retrained as therapy animals.',
                'negative_flavor' => 'The first windmill catches fire. The donkeys look smug.',
                'category' => 'economic',
            ],
            [
                'title' => 'Bankruptcy',
                'description' => 'The treasury is almost empty. The treasurer suggests checking under the throne cushions.',
                'difficulty' => 8,
                'positive_effects' => ['wealth' => 5, 'influence' => 1],
                'negative_effects' => ['wealth' => -3, 'happiness' => -1],
                'positive_flavor' => 'Creative accounting saves the day. Also, there WAS gold under the cushions.',
                'negative_flavor' => 'The kingdom is broke. You start accepting chickens as currency.',
                'category' => 'economic',
            ],
            [
                'title' => 'Salt Monopoly',
                'description' => 'A merchant offers to control all salt trade in the kingdom. Everything will cost more, but be better preserved.',
                'difficulty' => 6,
                'positive_effects' => ['wealth' => 4, 'food' => 1],
                'negative_effects' => ['happiness' => -2],
                'positive_flavor' => 'The salt trade flourishes. Food lasts longer. The merchant gets very, very rich.',
                'negative_flavor' => 'Salt prices triple. Bland food causes a kingdom-wide depression.',
                'category' => 'economic',
            ],
            [
                'title' => 'Dowry Negotiation',
                'description' => 'A marriage alliance requires a dowry. The bride\'s father is asking for "the nice castle, the one with the moat."',
                'difficulty' => 7,
                'positive_effects' => ['influence' => 4, 'wealth' => 2],
                'negative_effects' => ['wealth' => -3],
                'positive_flavor' => 'A reasonable dowry is agreed upon. Nobody gets a castle, but everyone gets wine.',
                'negative_flavor' => 'The negotiations collapse. The father takes his daughter and your best tablecloth.',
                'category' => 'economic',
            ],
            [
                'title' => 'Shipwreck Salvage',
                'description' => 'A merchant vessel has run aground near the coast. Its cargo of luxury goods bobs tantalizingly in the surf.',
                'difficulty' => 5,
                'positive_effects' => ['wealth' => 4, 'happiness' => 1],
                'negative_effects' => ['influence' => -1],
                'positive_flavor' => 'The cargo is recovered: silks, wines, and an extremely confused parrot.',
                'negative_flavor' => 'The original owners show up with lawyers. Medieval lawyers.',
                'category' => 'economic',
            ],
            [
                'title' => 'Fair Trade',
                'description' => 'The autumn fair is approaching. Every merchant in the kingdom is polishing their best lies.',
                'difficulty' => 4,
                'positive_effects' => ['wealth' => 3, 'happiness' => 2],
                'negative_effects' => ['happiness' => -1],
                'positive_flavor' => 'The fair is a resounding success. Only three cases of fraud reported.',
                'negative_flavor' => 'Rain turns the fairground to mud. Merchants and their lies sink slowly.',
                'category' => 'economic',
            ],

            // =============================================
            // SOCIAL (~25 cards)
            // =============================================
            [
                'title' => 'Plague Doctor',
                'description' => 'A plague doctor arrives with a beak mask and questionable remedies. His cure involves leeches and "positive thinking."',
                'difficulty' => 6,
                'positive_effects' => ['happiness' => 3, 'food' => 2],
                'negative_effects' => ['happiness' => -2],
                'positive_flavor' => 'The plague subsides. Whether it was the leeches or the positive thinking, nobody asks.',
                'negative_flavor' => 'His cures make things worse. The leeches escape and start their own practice.',
                'category' => 'social',
            ],
            [
                'title' => 'Traveling Bard',
                'description' => 'A bard requests permission to perform at court. His hit song is "My Horse Is Smarter Than Your Lord."',
                'difficulty' => 4,
                'positive_effects' => ['happiness' => 4],
                'negative_effects' => ['influence' => -1],
                'positive_flavor' => 'The court loves him. Even the lords laugh nervously at the horse song.',
                'negative_flavor' => 'Lord Pemberton recognizes himself in the lyrics. Drama ensues.',
                'category' => 'social',
            ],
            [
                'title' => 'Village Well',
                'description' => 'The village well has dried up. The village idiot claims to be a dowsing expert. He\'s pointing at a rock.',
                'difficulty' => 5,
                'positive_effects' => ['happiness' => 3, 'food' => 2],
                'negative_effects' => ['happiness' => -2],
                'positive_flavor' => 'A new well is dug. It wasn\'t where the idiot pointed, but he takes credit anyway.',
                'negative_flavor' => 'They dig where the idiot pointed. They find more rocks.',
                'category' => 'social',
            ],
            [
                'title' => 'Orphanage',
                'description' => 'The kingdom needs an orphanage. The proposed location is next to the pub. "For convenience," says the architect.',
                'difficulty' => 5,
                'positive_effects' => ['happiness' => 4, 'religion' => 1],
                'negative_effects' => ['wealth' => -1],
                'positive_flavor' => 'The orphanage is built and the children thrive. The pub does excellent business.',
                'negative_flavor' => 'Construction stalls. The orphans camp out in the pub. It\'s actually quite wholesome.',
                'category' => 'social',
            ],
            [
                'title' => 'Public Bath',
                'description' => 'A proposal to build public baths. The peasants are suspicious. "What\'s wrong with the river?"',
                'difficulty' => 4,
                'positive_effects' => ['happiness' => 3, 'religion' => 1],
                'negative_effects' => ['happiness' => -1],
                'positive_flavor' => 'The baths open. Cleanliness increases dramatically. Disease drops. The river misses them.',
                'negative_flavor' => 'Nobody uses the baths. The kingdom remains characterfully aromatic.',
                'category' => 'social',
            ],
            [
                'title' => 'Feast Preparations',
                'description' => 'A grand feast is being prepared. The cook requests "exotic meats." He won\'t specify which animals.',
                'difficulty' => 4,
                'positive_effects' => ['happiness' => 4, 'influence' => 1],
                'negative_effects' => ['food' => -2],
                'positive_flavor' => 'The feast is legendary. Nobody asks what was in the pie. Best not to.',
                'negative_flavor' => 'The cook over-orders. The castle smells of rotting swan for a week.',
                'category' => 'social',
            ],
            [
                'title' => 'Tournament',
                'description' => 'A jousting tournament is announced. Knights from across the land register. So does a farmer on a cow.',
                'difficulty' => 6,
                'positive_effects' => ['happiness' => 4, 'influence' => 2],
                'negative_effects' => ['security' => -1],
                'positive_flavor' => 'The tournament is spectacular. The farmer on the cow wins the hearts of the crowd.',
                'negative_flavor' => 'Three knights hospitalized. The cow is fine. The crowd demands more cow jousting.',
                'category' => 'social',
            ],
            [
                'title' => 'Rat Problem',
                'description' => 'The castle has a rat problem. A man with a pipe offers to lure them away with music. This sounds familiar.',
                'difficulty' => 5,
                'positive_effects' => ['happiness' => 3, 'food' => 2],
                'negative_effects' => ['happiness' => -2],
                'positive_flavor' => 'The rats follow the piper out of town. You remember to pay him this time.',
                'negative_flavor' => 'You forget to pay. He pipes a very different tune. Where are the children?',
                'category' => 'social',
            ],
            [
                'title' => 'School Proposal',
                'description' => 'A scholar proposes teaching peasant children to read. The lords are horrified. "What if they read the tax records?"',
                'difficulty' => 6,
                'positive_effects' => ['happiness' => 3, 'influence' => 2],
                'negative_effects' => ['influence' => -2],
                'positive_flavor' => 'A school is established. Literacy rises. The tax records are very eye-opening.',
                'negative_flavor' => 'The lords shut it down. Ignorance is maintained. The lords sleep well.',
                'category' => 'social',
            ],
            [
                'title' => 'Mystery Illness',
                'description' => 'Villagers report a strange illness: uncontrollable dancing. The afflicted seem confused but oddly fit.',
                'difficulty' => 5,
                'positive_effects' => ['happiness' => 3, 'religion' => 1],
                'negative_effects' => ['happiness' => -2],
                'positive_flavor' => 'The dancing plague passes after three days. The village has never been more limber.',
                'negative_flavor' => 'The dancing spreads to the castle. Court proceedings become very rhythmic.',
                'category' => 'social',
            ],
            [
                'title' => 'Stray Dogs',
                'description' => 'Packs of stray dogs roam the streets. The dogcatcher has been treed by them since Tuesday.',
                'difficulty' => 3,
                'positive_effects' => ['happiness' => 2, 'security' => 1],
                'negative_effects' => ['happiness' => -1],
                'positive_flavor' => 'The dogs are rounded up and adopted. The dogcatcher comes down from the tree.',
                'negative_flavor' => 'The dogs form an organized pack. They now have territory and a leader named Brian.',
                'category' => 'social',
            ],
            [
                'title' => 'Theatre Troupe',
                'description' => 'A theatre troupe wants to perform a play about the King. The script contains "mild satire." The King is not mild.',
                'difficulty' => 5,
                'positive_effects' => ['happiness' => 4, 'influence' => 1],
                'negative_effects' => ['influence' => -2],
                'positive_flavor' => 'The play is a hit. Even the King laughs, though nobody is sure if it\'s genuine.',
                'negative_flavor' => 'The King sees the play. The actors are now seeking asylum in France.',
                'category' => 'social',
            ],
            [
                'title' => 'Road Maintenance',
                'description' => 'The kingdom\'s roads are in terrible shape. One pothole has been granted its own parish.',
                'difficulty' => 5,
                'positive_effects' => ['wealth' => 2, 'happiness' => 2],
                'negative_effects' => ['wealth' => -1],
                'positive_flavor' => 'Roads are repaired. Travel time halves. The pothole is filled amid local mourning.',
                'negative_flavor' => 'Rain washes away repairs immediately. The pothole grows. It has ambitions.',
                'category' => 'social',
            ],
            [
                'title' => 'Ghost Sighting',
                'description' => 'The castle is reportedly haunted. Strange noises at night. The ghost is mostly complaining about the draft.',
                'difficulty' => 4,
                'positive_effects' => ['happiness' => 2, 'religion' => 2],
                'negative_effects' => ['happiness' => -1],
                'positive_flavor' => 'A priest exorcises the ghost. Its last words are a complaint about the wallpaper.',
                'negative_flavor' => 'The ghost stays. Staff demand hazard pay and refuse the night shift.',
                'category' => 'social',
            ],
            [
                'title' => 'Fashion Crisis',
                'description' => 'The Queen has decreed that pointy shoes are now unfashionable. Half the court can no longer walk properly.',
                'difficulty' => 3,
                'positive_effects' => ['happiness' => 2, 'influence' => 2],
                'negative_effects' => ['happiness' => -1],
                'positive_flavor' => 'Round-toed shoes become the rage. Cobblers work overtime. Walking improves.',
                'negative_flavor' => 'The court rebels. Shoes become pointier out of spite. Several toes are lost.',
                'category' => 'social',
            ],
            [
                'title' => 'Famine Warning',
                'description' => 'Crops are failing. The royal food advisor says we\'re fine. His mouth is full of cake.',
                'difficulty' => 8,
                'positive_effects' => ['food' => 5, 'happiness' => 2],
                'negative_effects' => ['food' => -3, 'happiness' => -2],
                'positive_flavor' => 'Emergency granaries are opened. Rationing works. Everyone loses a little weight.',
                'negative_flavor' => 'The famine hits hard. The food advisor is last seen fleeing with the cake.',
                'category' => 'social',
            ],
            [
                'title' => 'Love Triangle',
                'description' => 'A love triangle threatens to destabilize court. A duke loves a duchess who loves the stable boy who loves his horse.',
                'difficulty' => 5,
                'positive_effects' => ['happiness' => 3, 'influence' => 1],
                'negative_effects' => ['influence' => -2],
                'positive_flavor' => 'You broker a resolution. The duchess marries the duke. The stable boy marries his horse. Everyone\'s happy.',
                'negative_flavor' => 'The duke challenges the stable boy to a duel. The horse intervenes. It\'s chaos.',
                'category' => 'social',
            ],
            [
                'title' => 'Tavern Brawl',
                'description' => 'The biggest tavern brawl in kingdom history. Started over whether ale or mead is superior. Both sides make valid points.',
                'difficulty' => 4,
                'positive_effects' => ['happiness' => 2, 'security' => 1],
                'negative_effects' => ['happiness' => -1],
                'positive_flavor' => 'Order is restored. A compromise is reached: cider.',
                'negative_flavor' => 'The brawl becomes a full-blown cultural war. Mead vs. ale divides the kingdom.',
                'category' => 'social',
            ],
            [
                'title' => 'Royal Baby',
                'description' => 'A royal baby is born! The kingdom celebrates. The baby immediately throws up on the Archbishop.',
                'difficulty' => 3,
                'positive_effects' => ['happiness' => 4, 'influence' => 2],
                'negative_effects' => ['happiness' => -1],
                'positive_flavor' => 'The christening goes well. The baby is declared the cutest monarch-to-be in living memory.',
                'negative_flavor' => 'The baby cries for 72 hours straight. The castle staff consider emigrating.',
                'category' => 'social',
            ],
            [
                'title' => 'Alchemist\'s Promise',
                'description' => 'An alchemist claims he can turn lead into gold. He just needs funding. And more lead. And a week off.',
                'difficulty' => 7,
                'positive_effects' => ['wealth' => 5, 'influence' => 1],
                'negative_effects' => ['wealth' => -2],
                'positive_flavor' => 'He doesn\'t make gold, but invents a spectacular fireworks display. Close enough.',
                'negative_flavor' => 'He turns your gold into smoke. The laboratory explodes. He\'s gone.',
                'category' => 'social',
            ],
            [
                'title' => 'Lost Prince',
                'description' => 'A man claiming to be the long-lost prince appears at the gates. His evidence: a "royal birthmark" that could be a bruise.',
                'difficulty' => 6,
                'positive_effects' => ['influence' => 3, 'happiness' => 2],
                'negative_effects' => ['influence' => -2],
                'positive_flavor' => 'Investigation reveals he IS the prince. The bruise is a birthmark. Family reunion!',
                'negative_flavor' => 'He\'s a con artist from three counties over. The bruise is definitely a bruise.',
                'category' => 'social',
            ],
            [
                'title' => 'Bath Scandal',
                'description' => 'A lord has been spotted bathing twice in one month. His peers are appalled by this dangerous excess of hygiene.',
                'difficulty' => 3,
                'positive_effects' => ['happiness' => 2, 'influence' => 1],
                'negative_effects' => ['influence' => -1],
                'positive_flavor' => 'Monthly bathing becomes the new fashion. The kingdom smells marginally better.',
                'negative_flavor' => 'The lord is ostracized. He smells lovely but dines alone.',
                'category' => 'social',
            ],
            [
                'title' => 'Bear in the Castle',
                'description' => 'A bear has wandered into the throne room. It seems quite comfortable and is sitting on the throne.',
                'difficulty' => 6,
                'positive_effects' => ['happiness' => 3, 'security' => 2],
                'negative_effects' => ['happiness' => -1, 'security' => -1],
                'positive_flavor' => 'The bear is coaxed out with honey and employed as a castle mascot.',
                'negative_flavor' => 'The bear refuses to leave and is making surprisingly good policy decisions.',
                'category' => 'social',
            ],
            [
                'title' => 'Cheese Crisis',
                'description' => 'The kingdom\'s cheese supply has been cornered by one very ambitious dairy farmer. He demands a title.',
                'difficulty' => 4,
                'positive_effects' => ['food' => 3, 'happiness' => 2],
                'negative_effects' => ['food' => -1, 'happiness' => -1],
                'positive_flavor' => 'You break the cheese monopoly. Prices drop. The farmer gets a very minor title.',
                'negative_flavor' => 'Sir Cheese Lord now controls all dairy. The kingdom must negotiate for cheddar.',
                'category' => 'social',
            ],
            [
                'title' => 'Troubadour\'s Curse',
                'description' => 'A spurned troubadour has written a song so catchy it\'s stuck in everyone\'s head. Productivity has halved.',
                'difficulty' => 4,
                'positive_effects' => ['happiness' => 3],
                'negative_effects' => ['wealth' => -1, 'happiness' => -1],
                'positive_flavor' => 'A counter-song is composed. The curse is broken. Everyone hums something new.',
                'negative_flavor' => 'The song persists for six months. Workers hum it while doing nothing.',
                'category' => 'social',
            ],
        ];

        foreach ($cards as $card) {
            $card['sort_order'] = $order++;
            Card::create($card);
        }
    }
    private function seedEvents(): void
    {
        Event::truncate();

        $events = [
            [
                'title' => 'The Great Cheese Shortage',
                'effect' => 'A mysterious blight has struck the dairy herds. Cheese reserves dwindle and the people grow despondent. Each setback reminds them of what they\'ve lost.',
                'stat_modifiers' => ['happiness' => -1],
                'mechanic' => 'stat_modifier',
                'mechanic_data' => null,
            ],
            [
                'title' => 'Suspiciously Generous Harvest',
                'effect' => 'The crops have produced triple their normal yield. Nobody knows why. The scarecrows look smug. Every advisor receives a gift from the overflowing stores.',
                'stat_modifiers' => null,
                'mechanic' => 'grant_items',
                'mechanic_data' => ['random' => true],
            ],
            [
                'title' => 'The Fog',
                'effect' => 'An unnatural fog blankets the kingdom. Nobody can see more than ten feet ahead. All tasks become harder as advisors bump into things.',
                'stat_modifiers' => null,
                'mechanic' => 'reduce_dice',
                'mechanic_data' => ['amount' => 1],
            ],
            [
                'title' => 'The Doom Prophets',
                'effect' => 'Street preachers declare the end times are nigh. They\'ve been saying this for years, but they have pamphlets now. Difficult choices become even harder.',
                'stat_modifiers' => null,
                'mechanic' => 'altered_deal',
                'mechanic_data' => ['positive_cards' => 1, 'negative_cards' => 2],
            ],
            [
                'title' => 'Viking Tourism',
                'effect' => 'Vikings arrive, but not to raid. They\'re on holiday. They\'re very demanding guests. Security patrols stretch thin keeping up.',
                'stat_modifiers' => ['security' => -1],
                'mechanic' => 'stat_modifier',
                'mechanic_data' => null,
            ],
            [
                'title' => 'Pirate Gold',
                'effect' => 'A pirate ship runs aground and its crew vanishes, leaving behind chests of treasure. Finders keepers, apparently.',
                'stat_modifiers' => ['wealth' => 2],
                'mechanic' => 'stat_modifier',
                'mechanic_data' => null,
            ],
            [
                'title' => 'Royal Garage Sale',
                'effect' => 'The crown is selling off surplus equipment from the royal stores. Every advisor gets to rummage through the pile.',
                'stat_modifiers' => null,
                'mechanic' => 'grant_items',
                'mechanic_data' => ['random' => true],
            ],
            [
                'title' => 'Tournament of Complaints',
                'effect' => 'Every lord in the realm has arrived to air grievances simultaneously. Political maneuvering becomes treacherous with fewer favorable outcomes.',
                'stat_modifiers' => ['influence' => -1],
                'mechanic' => 'altered_deal',
                'mechanic_data' => ['positive_cards' => 1, 'negative_cards' => 2],
            ],
        ];

        foreach ($events as $event) {
            Event::create($event);
        }
    }
}
