<?php

namespace Database\Seeders;

use App\Models\Item;
use Illuminate\Database\Seeder;

class ItemSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            // =========================================
            // CO-OP / SINGLE-PLAYER ITEMS (single-use)
            // =========================================

            // === POSITIVE ITEMS (roll_bonus) — single-use ===
            [
                'name' => 'Royal Signet Ring',
                'description' => 'A gold ring bearing the King\'s seal. Use it to add authority to your next roll.',
                'effect' => ['bonus_type' => 'roll_bonus', 'bonus_value' => 1],
                'effect_type' => 'active',
                'is_negative' => false,
                'is_consumable' => false,
                'available_cooperative' => true,
                'available_duel' => false,
            ],
            [
                'name' => 'Blessed Rosary',
                'description' => 'Prayer beads consecrated by the Archbishop. Use them to bless your next roll.',
                'effect' => ['bonus_type' => 'roll_bonus', 'bonus_value' => 1],
                'effect_type' => 'active',
                'is_negative' => false,
                'is_consumable' => false,
                'available_cooperative' => true,
                'available_duel' => false,
            ],
            [
                'name' => 'Merchant\'s Ledger',
                'description' => 'A book of trade secrets and debts. Use it to gain an edge on your next roll.',
                'effect' => ['bonus_type' => 'roll_bonus', 'bonus_value' => 1],
                'effect_type' => 'active',
                'is_negative' => false,
                'is_consumable' => false,
                'available_cooperative' => true,
                'available_duel' => false,
            ],
            [
                'name' => 'Longbow of Sherwood',
                'description' => 'A masterwork yew longbow. Use it to add precision to your next challenge.',
                'effect' => ['bonus_type' => 'roll_bonus', 'bonus_value' => 1],
                'effect_type' => 'active',
                'is_negative' => false,
                'is_consumable' => false,
                'available_cooperative' => true,
                'available_duel' => false,
            ],
            [
                'name' => 'Knight\'s Oath',
                'description' => 'A sealed parchment binding a knight to your service. Use it to bolster your roll.',
                'effect' => ['bonus_type' => 'roll_bonus', 'bonus_value' => 1],
                'effect_type' => 'active',
                'is_negative' => false,
                'is_consumable' => false,
                'available_cooperative' => true,
                'available_duel' => false,
            ],
            [
                'name' => 'Crown of Laurels',
                'description' => 'A golden wreath of victory. Use it for a powerful boost to your next roll.',
                'effect' => ['bonus_type' => 'roll_bonus', 'bonus_value' => 2],
                'effect_type' => 'active',
                'is_negative' => false,
                'is_consumable' => false,
                'available_cooperative' => true,
                'available_duel' => false,
            ],
            [
                'name' => 'Excalibur\'s Shard',
                'description' => 'A sliver of the legendary blade, still humming with power. Use it to empower your roll.',
                'effect' => ['bonus_type' => 'roll_bonus', 'bonus_value' => 2],
                'effect_type' => 'active',
                'is_negative' => false,
                'is_consumable' => false,
                'available_cooperative' => true,
                'available_duel' => false,
            ],
            [
                'name' => 'Spy Network Map',
                'description' => 'A coded map of informant locations. Use it to gain intelligence for your next challenge.',
                'effect' => ['bonus_type' => 'roll_bonus', 'bonus_value' => 2],
                'effect_type' => 'active',
                'is_negative' => false,
                'is_consumable' => false,
                'available_cooperative' => true,
                'available_duel' => false,
            ],
            [
                'name' => 'Holy Grail Fragment',
                'description' => 'A shard from a sacred chalice. Use it to call upon divine aid for your roll.',
                'effect' => ['bonus_type' => 'roll_bonus', 'bonus_value' => 2],
                'effect_type' => 'active',
                'is_negative' => false,
                'is_consumable' => false,
                'available_cooperative' => true,
                'available_duel' => false,
            ],

            // === POSITIVE ITEMS (difficulty_reduction) — single-use ===
            [
                'name' => 'Cartographer\'s Charts',
                'description' => 'Detailed maps of the realm. Use them to reduce the difficulty of your next challenge.',
                'effect' => ['bonus_type' => 'difficulty_reduction', 'bonus_value' => 1],
                'effect_type' => 'active',
                'is_negative' => false,
                'is_consumable' => false,
                'available_cooperative' => true,
                'available_duel' => false,
            ],
            [
                'name' => 'Alchemist\'s Tonic',
                'description' => 'A shimmering elixir that sharpens the mind. Use it to make your challenge easier.',
                'effect' => ['bonus_type' => 'difficulty_reduction', 'bonus_value' => 1],
                'effect_type' => 'active',
                'is_negative' => false,
                'is_consumable' => false,
                'available_cooperative' => true,
                'available_duel' => false,
            ],
            [
                'name' => 'Papal Bull',
                'description' => 'A decree from Rome itself. Use it to significantly lower the difficulty ahead.',
                'effect' => ['bonus_type' => 'difficulty_reduction', 'bonus_value' => 2],
                'effect_type' => 'active',
                'is_negative' => false,
                'is_consumable' => false,
                'available_cooperative' => true,
                'available_duel' => false,
            ],

            // === CONSUMABLE / IMMEDIATE ITEMS (single-use, activate before roll) ===
            [
                'name' => 'Healing Draught',
                'description' => 'A warm herbal brew. Use it to restore +2 food to the realm.',
                'effect' => ['bonus_type' => 'stat_boost', 'bonus_value' => 2, 'stat' => 'food'],
                'effect_type' => 'active',
                'is_negative' => false,
                'is_consumable' => false,
                'available_cooperative' => true,
                'available_duel' => false,
            ],
            [
                'name' => 'War Horn',
                'description' => 'A mighty horn that rallies weary soldiers. Use it to recover a lost die.',
                'effect' => ['bonus_type' => 'heal_die', 'bonus_value' => 1],
                'effect_type' => 'active',
                'is_negative' => false,
                'is_consumable' => false,
                'available_cooperative' => true,
                'available_duel' => false,
            ],
            [
                'name' => 'Merchant\'s Windfall',
                'description' => 'A caravan of unexpected riches. Use it to gain +2 wealth.',
                'effect' => ['bonus_type' => 'stat_boost', 'bonus_value' => 2, 'stat' => 'wealth'],
                'effect_type' => 'active',
                'is_negative' => false,
                'is_consumable' => false,
                'available_cooperative' => true,
                'available_duel' => false,
            ],

            // === SCORE ITEMS (co-op only, single-use) ===
            [
                'name' => 'Royal Treasury Deed',
                'description' => 'An ancient deed to a forgotten royal vault. Use it for +15 renown.',
                'effect' => ['bonus_type' => 'score_bonus', 'bonus_value' => 15],
                'effect_type' => 'active',
                'is_negative' => false,
                'is_consumable' => false,
                'available_cooperative' => true,
                'available_duel' => false,
            ],
            [
                'name' => 'Chronicler\'s Quill',
                'description' => 'An enchanted quill that records your deeds. Use it for +10 renown.',
                'effect' => ['bonus_type' => 'score_bonus', 'bonus_value' => 10],
                'effect_type' => 'active',
                'is_negative' => false,
                'is_consumable' => false,
                'available_cooperative' => true,
                'available_duel' => false,
            ],
            [
                'name' => 'Bard\'s Lyre',
                'description' => 'A silver-stringed lyre whose songs spread your legend. Use it for +12 renown.',
                'effect' => ['bonus_type' => 'score_bonus', 'bonus_value' => 12],
                'effect_type' => 'active',
                'is_negative' => false,
                'is_consumable' => false,
                'available_cooperative' => true,
                'available_duel' => false,
            ],
            [
                'name' => 'Herald\'s Banner',
                'description' => 'A grand banner proclaiming your might. Use it for +15 renown.',
                'effect' => ['bonus_type' => 'score_bonus', 'bonus_value' => 15],
                'effect_type' => 'active',
                'is_negative' => false,
                'is_consumable' => false,
                'available_cooperative' => true,
                'available_duel' => false,
            ],
            [
                'name' => 'Pilgrim\'s Blessing',
                'description' => 'A holy relic from a wandering pilgrim. Use it for +10 renown.',
                'effect' => ['bonus_type' => 'score_bonus', 'bonus_value' => 10],
                'effect_type' => 'active',
                'is_negative' => false,
                'is_consumable' => false,
                'available_cooperative' => true,
                'available_duel' => false,
            ],
            // =========================================
            // DUEL-SPECIFIC ITEMS (single-use)
            // =========================================

            // === SELF-BUFF ITEMS ===
            [
                'name' => 'Battle Standard',
                'description' => 'Rally your forces with this war banner. Use it for +1 to your roll.',
                'effect' => ['bonus_type' => 'roll_bonus', 'bonus_value' => 1],
                'effect_type' => 'active',
                'is_negative' => false,
                'is_consumable' => false,
                'available_cooperative' => false,
                'available_duel' => true,
                'target' => 'self',
            ],
            [
                'name' => 'Enchanted Gauntlets',
                'description' => 'Gauntlets crackling with arcane energy. Use them for +2 to your roll.',
                'effect' => ['bonus_type' => 'roll_bonus', 'bonus_value' => 2],
                'effect_type' => 'active',
                'is_negative' => false,
                'is_consumable' => false,
                'available_cooperative' => false,
                'available_duel' => true,
                'target' => 'self',
            ],
            [
                'name' => 'Sage\'s Counsel',
                'description' => 'Wisdom from a court sage. Use it to reduce your difficulty by 1.',
                'effect' => ['bonus_type' => 'difficulty_reduction', 'bonus_value' => 1],
                'effect_type' => 'active',
                'is_negative' => false,
                'is_consumable' => false,
                'available_cooperative' => false,
                'available_duel' => true,
                'target' => 'self',
            ],
            [
                'name' => 'Divine Blessing',
                'description' => 'The gods smile upon you. Use it to reduce your difficulty by 2.',
                'effect' => ['bonus_type' => 'difficulty_reduction', 'bonus_value' => 2],
                'effect_type' => 'active',
                'is_negative' => false,
                'is_consumable' => false,
                'available_cooperative' => false,
                'available_duel' => true,
                'target' => 'self',
            ],
            [
                'name' => 'Healer\'s Touch',
                'description' => 'A healer\'s magic mends your kingdom. Use it for +2 to a random stat.',
                'effect' => ['bonus_type' => 'stat_boost', 'bonus_value' => 2],
                'effect_type' => 'active',
                'is_negative' => false,
                'is_consumable' => false,
                'available_cooperative' => false,
                'available_duel' => true,
                'target' => 'self',
            ],
            [
                'name' => 'Shield of Valor',
                'description' => 'An enchanted shield. Use it to block all negative card effects this round.',
                'effect' => ['bonus_type' => 'shield_negative', 'bonus_value' => 1],
                'effect_type' => 'active',
                'is_negative' => false,
                'is_consumable' => false,
                'available_cooperative' => false,
                'available_duel' => true,
                'target' => 'self',
            ],

            // === OPPONENT-DEBUFF ITEMS ===
            [
                'name' => 'Jinx Charm',
                'description' => 'A cursed trinket. Use it to reduce your opponent\'s roll by 1.',
                'effect' => ['bonus_type' => 'debuff_roll', 'bonus_value' => -1],
                'effect_type' => 'active',
                'is_negative' => false,
                'is_consumable' => false,
                'available_cooperative' => false,
                'available_duel' => true,
                'target' => 'opponent',
            ],
            [
                'name' => 'Curse of Weakness',
                'description' => 'Dark magic saps your rival\'s strength. Use it to reduce their roll by 2.',
                'effect' => ['bonus_type' => 'debuff_roll', 'bonus_value' => -2],
                'effect_type' => 'active',
                'is_negative' => false,
                'is_consumable' => false,
                'available_cooperative' => false,
                'available_duel' => true,
                'target' => 'opponent',
            ],
            [
                'name' => 'Sabotage Plans',
                'description' => 'Spies infiltrate the enemy. Use them to increase your opponent\'s difficulty by 1.',
                'effect' => ['bonus_type' => 'increase_difficulty', 'bonus_value' => 1],
                'effect_type' => 'active',
                'is_negative' => false,
                'is_consumable' => false,
                'available_cooperative' => false,
                'available_duel' => true,
                'target' => 'opponent',
            ],
            [
                'name' => 'Dark Ritual',
                'description' => 'A forbidden rite weakens your foe. Use it to increase their difficulty by 2.',
                'effect' => ['bonus_type' => 'increase_difficulty', 'bonus_value' => 2],
                'effect_type' => 'active',
                'is_negative' => false,
                'is_consumable' => false,
                'available_cooperative' => false,
                'available_duel' => true,
                'target' => 'opponent',
            ],
            [
                'name' => 'Spy\'s Report',
                'description' => 'Intelligence on the enemy. Use it to peek at your opponent\'s cards.',
                'effect' => ['bonus_type' => 'peek_cards', 'bonus_value' => 1],
                'effect_type' => 'active',
                'is_negative' => false,
                'is_consumable' => false,
                'available_cooperative' => false,
                'available_duel' => true,
                'target' => 'opponent',
            ],
            [
                'name' => 'Stat Drain',
                'description' => 'Siphon your rival\'s power. Use it to steal 1 point from a random enemy stat.',
                'effect' => ['bonus_type' => 'steal_stat', 'bonus_value' => 1],
                'effect_type' => 'active',
                'is_negative' => false,
                'is_consumable' => false,
                'available_cooperative' => false,
                'available_duel' => true,
                'target' => 'opponent',
            ],

        ];

        foreach ($items as $item) {
            Item::updateOrCreate(
                ['name' => $item['name']],
                $item
            );
        }
    }
}
